// The request: argv, checked. Nothing here reads a header or emits a line - it
// turns the command line into the globals the rest of the run reads, and prints
// the banner that says which request wrote a module.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "structgen.h"
#include "sg_args.h"
#include "sg_model.h"

const char *headers[MAXN], *roots[MAXN], *prefixes[MAXN], *snaps[MAXN], *writers[MAXN], *build, *out_ts, *out_swift, *out_hash_ts, *cwd = ".";
const char *target = "wasm32";
int nheaders, nroots, nprefixes, nsnaps, nwriters, print_hash, snapshot_only;
const char *build_name_end;
const char *build_flags;

// The header both generated modules start with.
void emit_banner(FILE *fp) {
    fprintf(fp, "// GENERATED by tools/structgen - do not edit.\n// build: %.*s; roots: ", (int)(build_name_end - build), build);
    for (int i = 0; i < nroots; i++) fprintf(fp, "%s%s", i ? ", " : "", roots[i]);
    fputc('\n', fp);
}

static void usage(void) {
    fputs("usage: structgen --cwd DIR --header H... --root T... --build NAME=FLAGS\n"
          "                 [--fields T=f1,f2,SIZE]... [--const PREFIX]...\n"
          "                 [--snapshot T]... [--count T.f=c]... [--writer T]... [--snapshot-only]\n"
          "                 [--target TRIPLE] [--ts OUT.ts] [--swift OUT.swift] [--hash-ts OUT.ts] [--print-hash]\n", stderr);
    exit(2);
}

void sg_args(int argc, char **argv) {
    for (int i = 1; i < argc; i++) {
        const char *a = argv[i];
        if (!strcmp(a, "--print-hash")) { print_hash = 1; continue; }
        if (!strcmp(a, "--snapshot-only")) { snapshot_only = 1; continue; }
        if (!strcmp(a, "--help") || !strcmp(a, "-h")) usage();
        if (strncmp(a, "--", 2)) die("unexpected argument %s", a);
        if (i + 1 >= argc || !strncmp(argv[i + 1], "--", 2)) die("%s needs a value", a);
        const char *v = argv[++i];
        if (!strcmp(a, "--header")) { if (nheaders == MAXN) die("too many --header"); headers[nheaders++] = v; }
        else if (!strcmp(a, "--root")) { if (nroots == MAXN) die("too many --root"); roots[nroots++] = v; }
        else if (!strcmp(a, "--const")) { if (nprefixes == MAXN) die("too many --const"); prefixes[nprefixes++] = v; }
        else if (!strcmp(a, "--snapshot")) { if (nsnaps == MAXN) die("too many --snapshot"); snaps[nsnaps++] = v; }
        else if (!strcmp(a, "--writer")) { if (nwriters == MAXN) die("too many --writer"); writers[nwriters++] = v; }
        else if (!strcmp(a, "--count")) {
            if (ncounts == MAXN) die("too many --count");
            Count *c = &counts[ncounts++];
            char *dot, *eq = NULL;
            c->type = xstrdup(v);
            if (!(dot = strchr(c->type, '.')) || !(eq = strchr(dot, '=')) || dot == c->type || eq == dot + 1 || !eq[1])
                die("--count must be TYPE.field=count_field");
            *dot = 0; *eq = 0;
            c->field = dot + 1; c->count = eq + 1;
        }
        else if (!strcmp(a, "--build")) { if (build) die("one --build per run (run once per build)"); build = v; }
        else if (!strcmp(a, "--ts")) out_ts = v;
        else if (!strcmp(a, "--swift")) out_swift = v;
        else if (!strcmp(a, "--hash-ts")) out_hash_ts = v;
        else if (!strcmp(a, "--target")) target = v;
        else if (!strcmp(a, "--cwd")) cwd = v;
        else if (!strcmp(a, "--fields")) {
            if (nspecs == MAXN) die("too many --fields");
            Spec *s = &specs[nspecs++];
            char *eq = strchr(s->type = xstrdup(v), '=');
            if (!eq || eq == s->type || !eq[1]) die("--fields must be TYPE=f1,f2,...");
            *eq = 0;
            for (char *tok = strtok(eq + 1, ","); tok; tok = strtok(NULL, ",")) {
                if (s->n == 256) die("too many fields for %s", s->type);
                s->names[s->n++] = tok;
            }
        }
        else die("unknown argument %s", a);
    }
    if (!nheaders || !nroots || !build) usage();
    if (!out_ts && !out_swift && !out_hash_ts && !print_hash) die("nothing to do: give --ts, --swift, --hash-ts and/or --print-hash");
    if (out_swift && !nsnaps) die("--swift without a --snapshot: Swift gets value snapshots, not accessors");
    const char *eq = strchr(build, '=');
    if (!eq || eq == build) die("--build must be NAME=FLAGS");
    build_name_end = eq;
    build_flags = eq + 1;
    out_ts = absolute(out_ts);   // output paths are relative to where we were started, not to --cwd
    out_swift = absolute(out_swift);
    out_hash_ts = absolute(out_hash_ts);
    if (chdir(cwd)) die("cannot cd to %s", cwd);
}
