// Embeds a compiled wasm module as a base64 TS module so every runtime
// (Deno edge, Node/tsx, browsers) can import it with zero asset plumbing.
// Regenerate with `make wasm` (rules) / `make wasm-bots` (bots) from cnitro/.
import { readFileSync, writeFileSync } from 'fs';
import { basename } from 'path';

const [src, dst, exportName = 'RULES_WASM_B64'] = process.argv.slice(2);
const bytes = readFileSync(src);
const b64 = bytes.toString('base64');

// ONE single-line literal, deliberately NOT chunked with `+`: V8 folds a
// chain of N string concatenations pairwise at parse time, allocating ~N
// intermediate copies — ~300MB of transient garbage for a 274KB embed —
// which trips the edge-function worker's memory kill during module import.
// A single literal parses with zero intermediate allocations.
writeFileSync(dst, `// GENERATED by cnitro/wasm/embed.mjs — do not edit.
// Source of truth: the cnitro C sources (see the Makefile target that
// builds ${basename(src)}). Rebuild with: cd cnitro && make ${basename(src) === 'bots.wasm' ? 'wasm-bots' : 'wasm'}
// ${bytes.length} bytes of wasm32.
export const ${exportName} = '${b64}';
`);
console.log(`embedded ${src} (${bytes.length} bytes) -> ${dst} as ${exportName}`);
