// Embeds a compiled wasm module as a base64 TS module so every runtime
// (Deno edge, Node/tsx, browsers) can import it with zero asset plumbing.
// Regenerate with `make wasm` (rules) / `make wasm-bots` (bots) from cnitro/.
// With --gzip the wasm is DEFLATE-compressed before base64 (~59% smaller than
// plain base64). The consumer inflates with fflate's sync gunzipSync, which
// works in every runtime including the browser (unlike node:zlib) and stays
// synchronous (unlike DecompressionStream) — so the shared engine.ts / browser
// clientGuards loaders keep their sync instantiate. Used for rules + guards;
// bots.wasm instead ships as a raw .gz static asset (see the Makefile).
import { readFileSync, writeFileSync } from 'fs';
import { gzipSync } from 'zlib';
import { basename } from 'path';

const args = process.argv.slice(2);
const gzip = args.includes('--gzip');
const [src, dst, exportName = 'RULES_WASM_B64'] = args.filter(a => a !== '--gzip');
const bytes = readFileSync(src);
const payload = gzip ? gzipSync(bytes, { level: 9 }) : bytes;
const b64 = payload.toString('base64');

// ONE single-line literal, deliberately NOT chunked with `+`: V8 folds a
// chain of N string concatenations pairwise at parse time, allocating ~N
// intermediate copies — ~300MB of transient garbage for a 274KB embed —
// which trips the edge-function worker's memory kill during module import.
// A single literal parses with zero intermediate allocations.
//
// Exported as a take-once FUNCTION, not a const: the sole caller
// (engine.ts / bots.ts) instantiates the module immediately and never needs
// the string again, so nulling the module-local lets the decoded literal's
// heap go per worker instead of pinning it for the isolate's lifetime.
writeFileSync(dst, `// GENERATED by cnitro/wasm/embed.mjs — do not edit.
// Source of truth: the cnitro C sources (see the Makefile target that
// builds ${basename(src)}). Rebuild with: cd cnitro && make ${basename(src) === 'bots.wasm' ? 'wasm-bots' : 'wasm'}
// ${bytes.length} bytes of wasm32${gzip ? `, gzipped to ${payload.length} then base64 — inflate with fflate gunzipSync` : ''}.
let b64: string | null = '${b64}';
// Returns the embed exactly once, freeing it — see cnitro/wasm/embed.mjs.
export function take${exportName}(): string {
    const s = b64;
    if (s === null) throw new Error('${exportName} already taken');
    b64 = null;
    return s;
}
`);
console.log(`embedded ${src} (${bytes.length} bytes${gzip ? ` -> gzip ${payload.length}` : ''}) -> ${dst} as ${exportName}`);
