/* What happened to a big game's picture: the 243 diagnostics
 * (docs/BIG_BOARD.md, "The picture diagnostics").
 *
 * The owner tests the 243 board on a second phone with no cable, so the app
 * itself has to say what a real send did to the bubble's picture. This module
 * is every rule of that report; the Swift gathers what only iOS knows (the
 * layout, the file, the participants) and hands it here.
 *
 *   - THE JPEG, from its bytes: size, components, the luma sampling factors
 *     (2x2 is 4:2:0), baseline or progressive, and the luma quantisation
 *     table, from which the quality is estimated (ubd_jpeg_parse).
 *   - THE GREYS, sampled where the kit samples them (bd_sample's cell
 *     centres and thresholds, reproduced here and held to the kit's own by
 *     tests/uttt_big_diag_test.c): per read class the mean, minimum, maximum
 *     and spread of the luminance, and a 16-bucket histogram (ubd_luma).
 *   - THE HISTORY, a ring of the last UBD_RING_MAX reads and sends in a fixed
 *     little-endian layout, so a send on one phone can be set beside the
 *     opening on the other afterwards (ubd_ring_*).
 *   - THE REPORT, plain text, one fact a line, every line at most
 *     UBD_LINE_MAX characters, the expectation beside each measured value and
 *     a "!" where they disagree (ubd_report).
 *
 * TESTFLIGHT ONLY, like the rest of the big game: every function here is
 * hidden (UBD_HIDDEN, for uti_msg_claim's reason in uttt_api.h) and
 * reached only through uttt_api.h's UTI_UNEXPORTED uti_big_diag_* entries,
 * which only Swift under UTTT_BIG_BOARD names; an App Store build
 * dead-strips all of it.
 *
 * NOTHING ALLOCATES. A hostile file can only produce a refusal: every read is
 * bounds-checked before it touches a byte. */
#ifndef UTTT_BIG_DIAG_H
#define UTTT_BIG_DIAG_H

#include <stdint.h>

/* Never exported from a framework that links this, so never kept unless
 * something calls it (uttt_api.h, UTI_UNEXPORTED). */
#define UBD_HIDDEN __attribute__((visibility("hidden")))

/* ------------------------------------------------------------- the JPEG */

#define UBD_SOF_BASELINE     0xC0
#define UBD_SOF_EXTENDED     0xC1
#define UBD_SOF_PROGRESSIVE  0xC2

/* Why a parse stopped. */
#define UBD_JPEG_OK          0
#define UBD_JPEG_NOT_JPEG   -1   /* no SOI at the start                       */
#define UBD_JPEG_TRUNCATED  -2   /* a segment runs past the end               */
#define UBD_JPEG_NO_FRAME   -3   /* the first scan came before any SOF        */
#define UBD_JPEG_BAD_FRAME  -4   /* an SOF with a length its fields do not fit */

/* The quality estimate's method (docs/BIG_BOARD.md): the luma table held to
 * ImageIO's own tables at quality 0.00 to 1.00 in steps of 0.01
 * (uttt_jpeg_imageio.inc, generated by tools/uttt_jpeg_imageio.c). An equal
 * table is EXACT, and its range is every step that writes that same table
 * (0.89, 0.90 and 0.91 share one). Otherwise the quality is interpolated on
 * the tables' sums, which fall as the quality rises; ImageIO takes a
 * continuous quality, so a transcoder's 0.893 lands between two steps. */
typedef struct {
    int      status;           /* UBD_JPEG_*                                  */
    int      width, height;
    int      components;       /* 1 grey, 3 YCbCr                             */
    int      precision;        /* bits a sample, 8 for every phone JPEG      */
    int      sof;              /* the frame marker, UBD_SOF_* or another C0-CF */
    int      h[4], v[4];       /* sampling factors of the first four components */
    int      jfif, exif, icc, adobe;   /* APP0 JFIF, APP1 Exif, APP2 ICC, APP14 */
    int      has_luma_table;   /* the luma component's table was found        */
    int      luma_bits;        /* 8, or 16 for a 16-bit table                 */
    uint16_t luma[64];         /* in file (zig-zag) order                     */
    int      luma_sum;
    /* the estimate, all in thousandths; -1 when there is no 8-bit table */
    int      q_exact;          /* 1: the table equals an ImageIO step's       */
    int      q_lo, q_hi;       /* exact: the steps writing this table         */
    int      q_est;            /* exact: q_lo; else the interpolation         */
    int      q_ijg;            /* the libjpeg scaling's quality (1..100) * 10 */
} UbdJpeg;

/* Parse `n` bytes of a JPEG up to its first scan. Returns ubd->status. */
UBD_HIDDEN int ubd_jpeg_parse(const uint8_t *p, long n, UbdJpeg *out);

/* "4:2:0", "4:4:4", "4:2:2", "4:4:0", "grey" or "other": the chroma
 * subsampling the components' factors make. */
UBD_HIDDEN const char *ubd_jpeg_chroma(const UbdJpeg *j);

/* The ImageIO table at step `pct` (0..100), file order, or NULL. */
UBD_HIDDEN const uint8_t *ubd_imageio_luma(int pct);

/* ------------------------------------------------------------- the greys */

#define UBD_CLASS_EMPTY  0
#define UBD_CLASS_X      1
#define UBD_CLASS_O      2
#define UBD_BUCKETS      16

typedef struct {
    int    n;
    double mean, sd;           /* of the luminance, (r + g + b) / 3           */
    int    min, max;
} UbdClass;

typedef struct {
    int      cells;            /* sampled, header row included: n * (n + 1)   */
    int      risky;            /* within UBD_RISKY of a threshold, the kit's  */
    int      min_margin;       /* 0..64                                        */
    UbdClass cls[3];           /* UBD_CLASS_*: how each class's greys came back */
    int      hist[UBD_BUCKETS];/* every sampled luminance, 16 wide a bucket   */
    /* THE WORST DEVIATION FROM NOMINAL: the largest distance of any cell's
     * luminance from its class's painted level (255, 128, 0), in thirds of a
     * level (a sum of r, g and b against 3 x the level), so it is exact. How
     * much room a fourth level would have is this number against the
     * spacing such a palette would leave. */
    int      worst_dev3;
} UbdLuma;

/* The painted level of a class: 255 empty, 128 X, 0 O (bubble_data.c). */
#define UBD_NOMINAL(c) ((c) == UBD_CLASS_EMPTY ? 255 : (c) == UBD_CLASS_X ? 128 : 0)

/* bd_sample's rule, reproduced: the kit's thresholds and risk margin. */
#define UBD_SUM_LO   (3 * 64)
#define UBD_SUM_HI   (3 * 191)
#define UBD_RISKY    16

/* Sample an RGBA picture (w x h, 4 bytes a pixel, sRGB) of an n x (n + 1)
 * cell grid where the kit does. 0, or -1 for a size the kit refuses. */
UBD_HIDDEN int ubd_luma(const uint8_t *rgba, int w, int h, int n, UbdLuma *out);

/* -------------------------------------------------------------- the ring */

#define UBD_ROLE_SENT     1    /* this device's own picture at didStartSending */
#define UBD_ROLE_OPENED   2    /* a picture read from a bubble                 */

/* A read's result: the kit's BD_E* (bubble_data.h) as its own number, and
 * two of ours. Swift maps the kit's error to these. */
#define UBD_R_OK          0
#define UBD_R_GEOMETRY    1
#define UBD_R_CAP         2
#define UBD_R_MAGIC       3
#define UBD_R_VERSION     4
#define UBD_R_KIND        5
#define UBD_R_LENGTH      6
#define UBD_R_CHECK       7
#define UBD_R_SYMBOL      8
#define UBD_R_IMAGE       9    /* CoreGraphics could not draw it             */
#define UBD_R_NO_PICTURE 10    /* the message carried no picture             */
#define UBD_R_NOT_READ   11    /* not sampled (a send records only the file) */
#define UBD_R_COUNT      12

/* The name a report prints for a UBD_R_*: "BD_EOK", "BD_ECHECK", ... */
UBD_HIDDEN const char *ubd_result_name(int r);

#define UBD_EV_CRC_KNOWN  1    /* the decoded board was held to the URL's CRC */
#define UBD_EV_CRC_SAME   2    /* ...and it was the same                      */
#define UBD_EV_Q_EXACT    4    /* the quality is an exact ImageIO table       */

typedef struct {
    int64_t  when;             /* unix seconds                                */
    int      role;             /* UBD_ROLE_*                                  */
    int      width, height;    /* the picture's pixels, 0 unknown             */
    long     bytes;            /* the file's, 0 for no file                   */
    int      q;                /* thousandths, -1 unknown                     */
    int      risky;            /* -1 not read                                 */
    int      min_margin;       /* -1 not read                                 */
    int      result;           /* UBD_R_*                                     */
    int      flags;            /* UBD_EV_*                                    */
} UbdEvent;

/* THE LAYOUT, little-endian, fixed:
 *   [0] 'U'  [1] 'R'  [2] UBD_RING_VERSION  [3] count (0..UBD_RING_MAX)
 *   then `count` records of UBD_REC_LEN bytes, the newest first:
 *   [0..3] when, uint32   [4] role   [5] q / 10, 0..100, 255 unknown
 *   [6..7] width  [8..9] height  [10..13] bytes, uint32
 *   [14..15] risky, 0xFFFF not read   [16] min margin, 255 not read
 *   [17] result   [18] flags   [19] zero
 * At most UBD_RING_BYTES; anything that is not this layout reads as empty. */
#define UBD_RING_VERSION  1
#define UBD_RING_MAX      20
#define UBD_REC_LEN       20
#define UBD_RING_BYTES    (4 + UBD_RING_MAX * UBD_REC_LEN)

/* Records in a ring (0 for one that is not the layout). */
UBD_HIDDEN int ubd_ring_count(const uint8_t *ring, int n);
/* Record `i` (0 the newest). 1, or 0 and nothing written. */
UBD_HIDDEN int ubd_ring_get(const uint8_t *ring, int n, int i, UbdEvent *out);
/* `ring` with `e` in front and the oldest past UBD_RING_MAX dropped, into
 * `out` (which may not overlap it). Bytes written, or -1 if cap is short. */
UBD_HIDDEN int ubd_ring_push(const uint8_t *ring, int n, const UbdEvent *e, uint8_t *out, int cap);

/* ------------------------------------------------------------ the report */

#define UBD_LINE_MAX  46

#define UBD_FROM_NONE       0  /* no message: the + menu                       */
#define UBD_FROM_SELECTED   1  /* conversation.selectedMessage at activation   */
#define UBD_FROM_DID_SELECT 2
#define UBD_FROM_DID_RECEIVE 3

#define UBD_WHO_UNKNOWN 0
#define UBD_WHO_ME      1      /* senderParticipantIdentifier == local         */
#define UBD_WHO_OTHER   2

/* What only iOS knows, gathered by the Swift. Strings may be NULL. A length
 * of -1 is a nil string. */
typedef struct {
    /* 1. who and where */
    const char *app_version, *app_build, *os_version, *model, *install;
    int64_t     now;           /* unix seconds                                */
    int         utc_offset;    /* seconds east of UTC, for the clock times    */
    int         from;          /* UBD_FROM_*                                  */
    int         who;           /* UBD_WHO_*                                   */
    int         pending;       /* message.isPending                           */
    const char *session;       /* the session's identity; printed as its CRC-32 */
    /* 2. the URL */
    const char *url;           /* the message's link, NULL for none           */
    const char *seat;          /* this device's seat in it, as the app says   */
    /* 3. the layout */
    const char *layout;        /* its class name                              */
    int         caption_len, subcaption_len, summary_len;
    int         has_image;
    int         image_w, image_h;   /* pixels: the CGImage's                  */
    int         image_scale_pct;    /* UIImage.scale * 100                    */
    int         has_file;
    const char *file_ext;
    long        file_bytes;
    const uint8_t *file;       /* the file's bytes, for the JPEG facts        */
    long        file_n;
    /* 4. the reading: the picture drawn at its own size, and the kit's verdict */
    const uint8_t *rgba;       /* NULL when there was no picture to draw      */
    int         rgba_w, rgba_h;
    int         read_result;   /* UBD_R_*                                     */
    int         read_cells, read_risky, read_min_margin;  /* the kit's reading */
    const uint8_t *symbols;    /* the decoded board, UTB_CELLS, or NULL       */
    int         read_us;       /* microseconds the kit's read took            */
    /* 5. the history */
    const uint8_t *ring;
    int         ring_n;
} UbdFacts;

/* The report, NUL-terminated, lines split by '\n'. Length written, or -1 when
 * `cap` is short (out is then a cut report ending in a whole line). */
UBD_HIDDEN int ubd_report(const UbdFacts *f, char *out, int cap);

/* The ring event the facts make (role UBD_ROLE_OPENED): what a diagnostics
 * opening, or any read of a bubble, adds to the history. */
UBD_HIDDEN UbdEvent ubd_event_of(const UbdFacts *f, int role);

#endif
