/* =============================================================================
 * Infinite Oracle — the hard-coded "why" proof generator (no AI calls)
 * Turns a candidate's merged MC path statistics (pathsBlob sidecar) into a
 * chess.com-style template explanation: the most likely concrete reply, the
 * dominant storylines as a probability tree, and a prose proof of why the
 * expected finish is what it is — including the counterfactual against the
 * best candidate. Every sentence is a localized template filled with real
 * measured MC probabilities; nothing here is generated by a model.
 * ========================================================================== */

import {
    OracleCandidate, OracleSnapshot, OraclePathStat,
} from './types';

/** t() shape from LocalizationContext, structurally typed so this module has
 *  no React dependency (headless-testable). */
export type TFn = (id: string, params?: Record<string, string | number>) => string;

/* ------------------------- token/label helpers ---------------------------- */

const VALUE_STR = ['?', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A'];
const SUIT_CHAR = ['♠', '♥', '♣', '♦'];

/** 0..51 card id (suit*13 + value-1, cordite_sim id space) → display token. */
export function cardIdToken(id: number, trump: number): string {
    if (id < 0 || id > 51) return '—';
    const suit = Math.floor(id / 13);
    const value = (id % 13) + 1;
    return `${VALUE_STR[value]}${SUIT_CHAR[suit]}${suit === trump ? '*' : ''}`;
}

/** Reply move (type + card) → localized phrase, e.g. "covers with 10♥". */
export function replyPhrase(t: TFn, type: number, card: number, trump: number): string {
    const tok = card < 52 ? cardIdToken(card, trump) : '';
    switch (type) {
        case 0: return t('oracle_reply_attack', { card: tok });
        case 1: return t('oracle_reply_cover', { card: tok });
        case 2: return t('oracle_reply_pass', { card: tok });
        case 3: return t('oracle_reply_pickup');
        default: return t('oracle_reply_good');
    }
}

/** Round-outcome symbol (cd_orc: 1..4) → localized clause. */
export function symPhrase(t: TFn, sym: number): string {
    switch (sym) {
        case 1: return t('oracle_ev_me_beat');
        case 2: return t('oracle_ev_me_pickup');
        case 3: return t('oracle_ev_opp_beat');
        default: return t('oracle_ev_opp_pickup');
    }
}

/** Cluster outcome → localized finish clause. Heads-up gets the crisp
 *  durak-probability phrasing (finish−1 IS the fool probability there);
 *  multiplayer gets a qualitative band so the clause carries meaning instead
 *  of repeating the number. */
function outcomePhrase(t: TFn, fin: number, numPlayers: number): string {
    if (numPlayers === 2) {
        const loss = Math.max(0, Math.min(1, fin - 1));
        if (loss <= 0.02) return t('oracle_out_win');
        if (loss >= 0.98) return t('oracle_out_loss');
        return t('oracle_out_mixed', { pct: Math.round(loss * 100) });
    }
    const base = (numPlayers + 1) / 2;
    if (fin <= 1.15) return t('oracle_out_first');
    if (fin >= numPlayers - 0.15) return t('oracle_out_loss');
    if (fin <= base - 0.25) return t('oracle_out_strong', { place: fin.toFixed(2) });
    if (fin >= base + 0.25) return t('oracle_out_bad', { place: fin.toFixed(2) });
    return t('oracle_out_mid', { place: fin.toFixed(2) });
}

/** Round-symbol sequence → compressed clause chain: repeated symbols fold
 *  into "you beat the round (3× in a row)", and a 4-round chain of a game
 *  whose playouts run visibly longer gets a "…and the game runs on" tail so
 *  a truncated prefix never reads as the whole story. */
function chainPhrase(t: TFn, seq: number[], meanRounds: number): string {
    if (seq.length === 0) return t('oracle_ev_resolved');
    const clauses: string[] = [];
    let i = 0;
    while (i < seq.length) {
        let j = i;
        while (j + 1 < seq.length && seq[j + 1] === seq[i]) j++;
        const k = j - i + 1;
        const phrase = symPhrase(t, seq[i]);
        clauses.push(k > 1 ? t('oracle_why_repeat', { clause: phrase, k }) : phrase);
        i = j + 1;
    }
    let chain = clauses.join(t('oracle_why_then'));
    if (seq.length >= 4 && meanRounds > 5) {
        chain += t('oracle_why_continues', { r: Math.round(meanRounds) });
    }
    return chain;
}

/* ------------------------------ tree view --------------------------------- */

export interface WhyTreeNode {
    sym: number | null;        // null = "playout resolved here"
    share: number;             // fraction of this candidate's playouts through this node
    fin: number | null;        // mean finish over playouts ENDING here (leaves only)
    children: WhyTreeNode[];
}

/** Fold the flat path clusters into a prefix tree (the storyline tree view).
 *  Cluster seqs are ≤4 symbols; a cluster ending before round 4 is a leaf
 *  with its own fin. Shares are relative to the candidate's folded total. */
export function buildWhyTree(paths: OraclePathStat[], total: number): WhyTreeNode[] {
    interface Mut { sym: number | null; n: number; finSum: number; leafN: number; kids: Map<number | -1, Mut>; }
    const root: Mut = { sym: null, n: 0, finSum: 0, leafN: 0, kids: new Map() };
    for (const p of paths) {
        let node = root;
        for (const s of p.seq) {
            let kid = node.kids.get(s);
            if (!kid) { kid = { sym: s, n: 0, finSum: 0, leafN: 0, kids: new Map() }; node.kids.set(s, kid); }
            kid.n += p.n;
            node = kid;
        }
        node.finSum += p.fin * p.n;
        node.leafN += p.n;
    }
    const freeze = (m: Mut): WhyTreeNode => ({
        sym: m.sym,
        share: total > 0 ? m.n / total : 0,
        fin: m.leafN > 0 ? m.finSum / m.leafN : null,
        children: [...m.kids.values()].sort((a, b) => b.n - a.n).map(freeze),
    });
    return [...root.kids.values()].sort((a, b) => b.n - a.n).map(freeze);
}

/* ---------------------------- the proof text ------------------------------- */

export interface WhyExplanation {
    headline: string;          // one-line verdict, chess.com-comment style
    reply: string | null;      // "Most likely reply: covers with 10♥ (43%)"
    proof: string[];           // the storyline proof paragraphs
    versusBest: string | null; // counterfactual vs the best candidate
    marginals: string;         // pickup/trump/round rates line
    tree: WhyTreeNode[];       // the storyline tree (for the tree view)
}

const pct = (x: number) => Math.round(x * 100);

/** Build the full template explanation for one clicked candidate. Pure and
 *  synchronous — computed on click only, never during batch streaming. */
export function explainCandidate(
    t: TFn,
    c: OracleCandidate,
    best: OracleCandidate | null,
    s: OracleSnapshot,
): WhyExplanation | null {
    // Exact regime: the proof IS the solver.
    if (c.verdict === 'win' || c.verdict === 'loss' || c.verdict === 'draw') {
        const depth = c.verdictVal != null ? 1000 - Math.abs(c.verdictVal) : null;
        return {
            headline: t(`oracle_why_exact_${c.verdict}`, { d: depth ?? '?' }),
            reply: null,
            proof: [t('oracle_why_exact_proof')],
            versusBest: null,
            marginals: '',
            tree: [],
        };
    }
    const why = c.why;
    if (!why || why.agg.n === 0 || c.mean == null) return null;
    const np = s.numPlayers;
    const total = why.agg.n;

    // ---- headline: delta-to-best framing --------------------------------
    const delta = best && best.mean != null ? c.mean - best.mean : 0;
    let headline: string;
    if (!best || best.key === c.key || delta < 0.0001) {
        headline = t('oracle_why_best', { ef: c.mean.toFixed(2) });
    } else {
        headline = t('oracle_why_delta', {
            ef: c.mean.toFixed(2), best: best.label, delta: delta.toFixed(2),
        });
    }

    // ---- most likely reply ------------------------------------------------
    let reply: string | null = null;
    if (why.replies.length > 0) {
        const r = why.replies[0];
        reply = t('oracle_why_reply', {
            phrase: replyPhrase(t, r.type, r.card, s.belief?.trump ?? -1),
            pct: pct(r.n / total),
        });
    }

    // ---- storyline proof: the dominant clusters as clause chains ----------
    const proof: string[] = [];
    const shown = why.paths.slice(0, 3);
    for (const p of shown) {
        const share = pct(p.n / total);
        if (share < 5) continue;                       // noise floor
        proof.push(t('oracle_why_path', {
            pct: share,
            chain: chainPhrase(t, p.seq, why.agg.rnds),
            outcome: outcomePhrase(t, p.fin, np),
        }));
    }

    // ---- counterfactual vs best ------------------------------------------
    let versusBest: string | null = null;
    if (best && best.key !== c.key && best.mean != null && best.why && delta >= 0.0001) {
        const bw = best.why;
        // A noise-level gap gets the honest no-single-cause line — never
        // dress up a 0.04 in causal language.
        if (delta < 0.05) {
            return {
                headline, reply, proof,
                versusBest: t('oracle_why_vs_noise', { best: best.label, delta: delta.toFixed(2) }),
                marginals: t('oracle_why_marginals', {
                    n: total,
                    mepk: why.agg.mepk.toFixed(2), oppk: why.agg.oppk.toFixed(2),
                    metr: why.agg.metr.toFixed(2), opptr: why.agg.opptr.toFixed(2),
                    rnds: why.agg.rnds.toFixed(1),
                }),
                tree: buildWhyTree(why.paths, total),
            };
        }
        // name the biggest measured driver of the gap
        const dPk = why.agg.mepk - bw.agg.mepk;
        const dTr = why.agg.metr - bw.agg.metr;
        const dOp = bw.agg.oppk - why.agg.oppk;
        if (dPk >= Math.max(dTr, dOp, 0.05)) {
            versusBest = t('oracle_why_vs_pickup', {
                best: best.label, a: why.agg.mepk.toFixed(2), b: bw.agg.mepk.toFixed(2),
                delta: delta.toFixed(2),
            });
        } else if (dTr >= Math.max(dOp, 0.05)) {
            versusBest = t('oracle_why_vs_trump', {
                best: best.label, a: why.agg.metr.toFixed(2), b: bw.agg.metr.toFixed(2),
                delta: delta.toFixed(2),
            });
        } else if (dOp >= 0.05) {
            versusBest = t('oracle_why_vs_opp', {
                best: best.label, a: bw.agg.oppk.toFixed(2), b: why.agg.oppk.toFixed(2),
                delta: delta.toFixed(2),
            });
        } else {
            // storylines diverge without a single dominant marginal: point at
            // the first round where the dominant clusters differ.
            const a = why.paths[0]?.seq ?? [];
            const b = bw.paths[0]?.seq ?? [];
            let i = 0;
            while (i < a.length && i < b.length && a[i] === b[i]) i++;
            if (i < a.length || i < b.length) {
                versusBest = t('oracle_why_vs_diverge', {
                    best: best.label, round: i + 1,
                    here: i < a.length ? symPhrase(t, a[i]) : t('oracle_ev_resolved'),
                    there: i < b.length ? symPhrase(t, b[i]) : t('oracle_ev_resolved'),
                    delta: delta.toFixed(2),
                });
            } else {
                versusBest = t('oracle_why_vs_noise', { best: best.label, delta: delta.toFixed(2) });
            }
        }
    }

    // ---- marginals line ---------------------------------------------------
    const marginals = t('oracle_why_marginals', {
        n: total,
        mepk: why.agg.mepk.toFixed(2), oppk: why.agg.oppk.toFixed(2),
        metr: why.agg.metr.toFixed(2), opptr: why.agg.opptr.toFixed(2),
        rnds: why.agg.rnds.toFixed(1),
    });

    return {
        headline, reply, proof, versusBest, marginals,
        tree: buildWhyTree(why.paths, total),
    };
}
