// A structgen output is a BUILD OUTPUT. It is not committed, and this is the
// gate that keeps it that way.
//
// The repo has already paid for the other arrangement once. `verify.wasm` was
// committed under tools/structgen/gen/ with `diff -x verify.wasm` excusing it
// from the freshness check, and the exclusion is exactly what let it rot: it
// still held the layouts anim_plan.h had before AnimPlan grew, while
// `gen.sh --check` reported everything fresh (f6338351). An artifact nothing
// compares is an artifact nothing keeps fresh - and the cheapest way to have
// nothing to compare is to have nothing committed.
//
// So the modules tools/structgen writes are generated by the build now, in CI
// and locally, and re-committing one must be impossible to do by accident.
// Three facts, checked here:
//
//   1. git tracks NO file under a directory gen.sh writes into.
//   2. every such directory is ignored, so a regenerated tree is clean and a
//      `git add -A` cannot sweep one back in.
//   3. nothing else in the repo expects them to be tracked (the ignore rules
//      and the generator agree about which directories those are).
//
// The directories come from `gen.sh --print-dirs` rather than from a list kept
// here: the generator is asked what it generates. That flag needs no toolchain,
// which is why this gate can live in the fast lane and run on every pull
// request while the libclang-shaped checks stay in wasm.yml.
//
// Pure test - no Postgres, no network, no compiler.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { resolve, join } from 'node:path';

const REPO = resolve(import.meta.dirname, '../..');
const GEN_SH = 'tools/structgen/gen.sh';

const run = (cmd: string, args: string[]) =>
    execFileSync(cmd, args, { cwd: REPO, encoding: 'utf8', env: { ...process.env, GIT_OPTIONAL_LOCKS: '0' } });

const git = (...args: string[]) => run('git', args);

/** What gen.sh says it writes into, repo-relative. */
function generatedDirs(): string[] {
    return run('bash', [GEN_SH, '--print-dirs']).split('\n').map((s) => s.trim()).filter(Boolean);
}

test('gen.sh answers for its own output directories', () => {
    const dirs = generatedDirs();
    // Four today: the TS the web, server and e2e import; the Swift FoolishKit
    // compiles; the Kotlin a JVM client would; the generator's own fixtures.
    // The count is asserted so that a
    // --print-dirs that starts answering with nothing fails HERE rather than
    // making the two checks below pass over an empty list.
    assert.ok(dirs.length >= 3, `${GEN_SH} --print-dirs answered with ${dirs.length} directories: ${dirs.join(', ')}`);
    for (const d of dirs) {
        assert.ok(!d.startsWith('/') && !d.includes('..'),
            `${d} is not a repo-relative directory - this gate resolves these against the repo root`);
    }
});

test('no structgen output is tracked in the repo', () => {
    const dirs = generatedDirs();
    const tracked = git('ls-files', '--', ...dirs).split('\n').filter(Boolean);
    assert.deepEqual(tracked, [],
        'these are build outputs and must not be committed. Every build writes them\n'
        + '(tools/structgen/gen.sh), so a committed copy is a copy nothing keeps fresh -\n'
        + 'which is how verify.wasm rotted for months. Remove them with:\n'
        + `  git rm --cached ${tracked.join(' ')}\n`);
});

test('every structgen output directory is ignored', () => {
    const notIgnored: string[] = [];
    for (const dir of generatedDirs()) {
        // A path that need not exist: check-ignore answers about the path, not
        // about a file, so this holds on a tree nothing has generated into yet.
        const probe = join(dir, 'structgen_output_probe');
        try {
            git('check-ignore', '-q', '--no-index', '--', probe);
        } catch {
            notIgnored.push(dir);
        }
    }
    assert.deepEqual(notIgnored, [],
        'these directories are written by every build but are not ignored, so a\n'
        + "regenerated tree shows up as untracked and one `git add -A` puts them back:\n"
        + `  ${notIgnored.join('\n  ')}\n`);
});
