-- Realtime: drop `tmp_allow_all`, a blanket SELECT policy live on hosted.
--
-- Found by reading the hosted catalog on 2026-09-18:
--
--   policyname     | roles           | cmd    | qual
--   tmp_allow_all  | {authenticated} | SELECT | true
--
-- Realtime admits a private channel join when a SELECT policy on
-- realtime.messages passes for that topic, so a policy whose USING clause is
-- `true` admits EVERY authenticated user to EVERY private topic. That includes
-- `gu-{game_id}-{user_id}`, the per-seat animation stream, whose payload is the
-- masked view of that ONE seat: a signed-in stranger who knows a game id and a
-- user id could subscribe to another player's stream and watch their hand.
--
-- It also explains why live web play worked at all. The real gu- policy took
-- the topic apart with split_part(topic, '-', 3), which on a hyphenated UUID is
-- the first 8 hex digits and never equals auth.uid(), so it refused everyone,
-- owner included (fixed in 20260917120000). With that policy matching nobody,
-- `tmp_allow_all` was the one carrying every join on hosted.
--
-- ORDER MATTERS. Dropping this alone would have taken live play down with it,
-- because the policy that should admit a seated player only started matching in
-- 20260917120000. That migration runs first (its timestamp is earlier), so by
-- the time this one lands, the exact-topic policies are already in place.
--
-- The policy was never in this repo: seed.sql has never defined it, so a fresh
-- database has nothing to drop and this is a no-op there. It exists only on the
-- hosted project, where it was presumably added by hand while debugging.
-- e2e/realtime_channel_auth.test.ts now fails if any policy on
-- realtime.messages admits a topic unconditionally, so one cannot come back
-- unnoticed.

DROP POLICY IF EXISTS "tmp_allow_all" ON "realtime"."messages";
