/* Writes src/uttt_jpeg_imageio.inc: ImageIO's JPEG luma quantisation table at
 * every quality from 0.00 to 1.00 in steps of 0.01, which the 243
 * diagnostics hold a picture's table to (src/uttt_big_diag.h).
 *
 *     make -C uttt/c jpeg-imageio      (macOS: ImageIO)
 *
 * The tables do not depend on the picture (checked on a ramp, a flat white
 * 729 x 732 and noise at every step, 2026-10-02), so one small grey picture
 * makes them. tests/uttt_big_diag_imageio.c runs this again and fails when
 * the committed file is not what ImageIO writes today. */
#include "../src/uttt_big_diag.h"
#include <CoreFoundation/CoreFoundation.h>
#include <CoreGraphics/CoreGraphics.h>
#include <ImageIO/ImageIO.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static CGImageRef grey_image(int side)
{
    uint8_t *px = malloc((size_t)side * side * 4);
    for (int i = 0; i < side * side; i++) {
        uint8_t v = (uint8_t)((i * 37) & 255);
        px[4 * i] = px[4 * i + 1] = px[4 * i + 2] = v;
        px[4 * i + 3] = 255;
    }
    CGColorSpaceRef cs = CGColorSpaceCreateWithName(kCGColorSpaceSRGB);
    CGContextRef ctx = CGBitmapContextCreate(px, (size_t)side, (size_t)side, 8, (size_t)side * 4, cs,
                                             (CGBitmapInfo)kCGImageAlphaNoneSkipLast);
    CGImageRef img = CGBitmapContextCreateImage(ctx);
    CGContextRelease(ctx);
    CGColorSpaceRelease(cs);
    free(px);
    return img;
}

/* The JPEG ImageIO writes for `img` at `q`, as Messages' UIImageJPEGRepresentation does. */
static CFDataRef jpeg_of(CGImageRef img, double q)
{
    CFMutableDataRef d = CFDataCreateMutable(NULL, 0);
    CGImageDestinationRef dst = CGImageDestinationCreateWithData(d, CFSTR("public.jpeg"), 1, NULL);
    CFNumberRef qn = CFNumberCreate(NULL, kCFNumberDoubleType, &q);
    const void *k[] = { kCGImageDestinationLossyCompressionQuality };
    const void *v[] = { qn };
    CFDictionaryRef opts = CFDictionaryCreate(NULL, k, v, 1, &kCFTypeDictionaryKeyCallBacks,
                                              &kCFTypeDictionaryValueCallBacks);
    CGImageDestinationAddImage(dst, img, opts);
    CGImageDestinationFinalize(dst);
    CFRelease(opts);
    CFRelease(qn);
    CFRelease(dst);
    return d;
}

int main(int argc, char **argv)
{
    FILE *f = argc > 1 ? fopen(argv[1], "w") : stdout;
    if (!f) { fprintf(stderr, "uttt_jpeg_imageio: cannot write %s\n", argv[1]); return 1; }
    CGImageRef img = grey_image(32);
    fprintf(f, "/* GENERATED by tools/uttt_jpeg_imageio.c (make jpeg-imageio): ImageIO's\n"
               " * luma quantisation table at quality 0.00 to 1.00, step 0.01, in file\n"
               " * (zig-zag) order, and each table's sum. Do not edit; regenerate.\n"
               " * tests/uttt_big_diag_imageio.c holds it to ImageIO on every run. */\n");
    fprintf(f, "static const uint8_t ubd_imageio[101][64] = {\n");
    int sums[101];
    for (int pct = 0; pct <= 100; pct++) {
        CFDataRef d = jpeg_of(img, pct / 100.0);
        UbdJpeg j;
        if (ubd_jpeg_parse(CFDataGetBytePtr(d), CFDataGetLength(d), &j) != UBD_JPEG_OK ||
            !j.has_luma_table || j.luma_bits != 8) {
            fprintf(stderr, "uttt_jpeg_imageio: no 8-bit luma table at %d\n", pct);
            return 1;
        }
        sums[pct] = j.luma_sum;
        fprintf(f, "    /* %3d */ {", pct);
        for (int k = 0; k < 64; k++) fprintf(f, "%s%d", k ? "," : "", j.luma[k]);
        fprintf(f, "},\n");
        CFRelease(d);
    }
    fprintf(f, "};\nstatic const int ubd_imageio_sum[101] = {\n");
    for (int pct = 0; pct <= 100; pct++)
        fprintf(f, "%s%d%s", pct % 10 == 0 ? "    " : " ", sums[pct], pct == 100 ? "\n" : pct % 10 == 9 ? ",\n" : ",");
    fprintf(f, "};\n");
    CGImageRelease(img);
    if (f != stdout) fclose(f);
    return 0;
}
