// FStrings.swift — localization access (§5.5: all text through the table from
// day one; en/ru/ko/zh/vi). v1 backs this with an in-code trilingual table so every
// string is localized immediately. Milestone E4 (scripts/gen_ios_strings.mjs)
// replaces this table with a generated Localizable.xcstrings String Catalog
// merged from the web's src/localization/strings.ts — the API (`FStrings.t`)
// stays, the backing store changes. Keys keep the web's names; iOS-only keys
// use the `ios.` prefix (§16.E4).

import Foundation

public enum AppLanguage: String, CaseIterable, Sendable {
    // No "System": the owner found it confusing. We resolve the OS locale ONCE
    // (default English) and land on a concrete language, which the user can then
    // switch among these (see FStrings.override).
    //
    // ROUND 30 added zh and vi. Adding one is three edits and a table: a case
    // here, its own name in `display`, a prefix in `systemDetected`, and the
    // 213 keys. Nothing else in the app enumerates languages by hand - the
    // settings pickers and LocalizationTests all walk `allCases`, so a new
    // language appears in the UI and is checked for completeness the moment it
    // is declared.
    case en, ru, ko, zh, vi
    /// Each language names ITSELF - a picker that said "Chinese" in English to
    /// somebody who cannot read English would be pointing at the way out in a
    /// language they do not speak.
    public var display: String {
        switch self {
        case .en: return "English"
        case .ru: return "Русский"
        case .ko: return "한국어"
        case .zh: return "中文"
        case .vi: return "Tiếng Việt"
        }
    }
}

public enum FStrings {
    /// The active language (§16.E3). On first use we detect it from the OS locale
    /// (English fallback) and land on a concrete choice; once the user picks one
    /// it is persisted. There is no "System" option any more.
    public static var override: AppLanguage {
        get {
            if let raw = UserDefaults.standard.string(forKey: "ios.language"),
               let lang = AppLanguage(rawValue: raw) { return lang }
            return systemDetected
        }
        set { UserDefaults.standard.set(newValue.rawValue, forKey: "ios.language") }
    }

    /// The OS locale mapped onto our three languages, English by default. This is
    /// the initial `override` until the user makes an explicit choice.
    private static var systemDetected: AppLanguage {
        let pref = Locale.preferredLanguages.first ?? "en"
        if pref.hasPrefix("ru") { return .ru }
        if pref.hasPrefix("ko") { return .ko }
        // Any Chinese: the table is Simplified, and a Traditional reader lands
        // somewhere they can read rather than in English. `zh-Hans`, `zh-Hant`,
        // `zh-HK` and a bare `zh` all begin the same way, which is the whole
        // reason this is a prefix test and not an equality one.
        if pref.hasPrefix("zh") { return .zh }
        if pref.hasPrefix("vi") { return .vi }
        return .en
    }

    private static var activeLang: String { override.rawValue }

    /// Look up `key`, interpolating {name}-style placeholders from `args`.
    public static func t(_ key: String, _ args: [String: String] = [:]) -> String {
        let lang = activeLang
        var s = table[lang]?[key] ?? table["en"]?[key] ?? key
        // Sorted, because sequential replacement is order-sensitive: a value
        // containing "{otherKey}" would or would not be substituted depending on
        // which key ran first, and Dictionary order is a per-launch accident.
        // No call site relies on that today; sorting makes it impossible to
        // start relying on it by accident.
        for k in args.keys.sorted() {
            guard let v = args[k] else { continue }
            s = s.replacingOccurrences(of: "{\(k)}", with: v)
        }
        return s
    }

    /// A human reason for a rejected move (1.0(4)). The kernel's 21
    /// ENGINE_REJECT_* codes (c/src/game.h, surfaced by fio_last_reject) fold
    /// into a handful of clear, non-code-y sentences. `code` 0 / unknown falls
    /// back to the generic "That move isn't allowed."
    public static func rejectReason(_ code: Int) -> String {
        switch code {
        case 1, 4, 8, 18: return t("ios.rej.turn")     // NOT_PLAYING/NOT_DEFENDER/NOT_FIRST_ATTACKER/NOT_IN_STATUS
        case 2:            return t("ios.rej.pickone")  // EMPTY
        case 3:            return t("ios.rej.defending")// IS_DEFENDER
        case 5, 6:         return t("ios.rej.notyours") // NOT_IN_HAND/DUPLICATES
        case 7, 9:         return t("ios.rej.addrank")  // NOT_SAME_VALUE/VALUE_NOT_ON_TABLE
        case 11, 12, 13, 15: return t("ios.rej.cover")  // NO_UNCOVERED/ATTACK_NOT_ON_TABLE/CANNOT_COVER/COVER_PRESENT
        case 10, 17, 21:   return t("ios.rej.capacity") // DEFENDER_CAPACITY/PASS_CAPACITY/PASS_OVERFLOW
        case 16:           return t("ios.rej.passrank") // PASS_VALUES
        case 20:           return t("ios.rej.mustattack")// FIRST_MUST_ATTACK
        case 19:           return t("ios.rej.alreadygood")// ALREADY_GOOD
        case 14:           return t("ios.rej.notake")   // NO_TABLE_CARDS
        // 22 (PASS_DISABLED, the podkidnoy variant) deliberately has no line of
        // its own: a table without the transfer never offers one, so this is
        // unreachable from the menu, and a message about passing is the one
        // thing such a game must not put on screen. It falls to the generic
        // "that move isn't allowed" with everything else that cannot happen.
        default:           return t("ios.reject")
        }
    }

    // Spoken card names for VoiceOver (round-5 m2): the visible strings were
    // localized while every accessibilityLabel was English, so a ru/ko VoiceOver
    // user got an English board. One builder, shared by every board component,
    // so "queen of spades" / "дама, пики" / "스페이드 퀸" cannot drift apart
    // between the hand, the battles and the deck. Rank indices are the kernel's
    // (9='10' … 13='A', CardRank.label's mapping); numeric ranks stay digits,
    // which VoiceOver reads in its own language already.

    public static func spokenRank(_ value: Int) -> String {
        switch value {
        case 13: return t("ios.rank.ace")
        case 12: return t("ios.rank.king")
        case 11: return t("ios.rank.queen")
        case 10: return t("ios.rank.jack")
        case 9:  return t("ios.rank.ten")
        default: return String(value + 1)
        }
    }

    public static func spokenSuit(_ suit: Suit) -> String {
        switch suit {
        case .spades: return t("ios.suit.spades")
        case .hearts: return t("ios.suit.hearts")
        case .clubs: return t("ios.suit.clubs")
        case .diamonds: return t("ios.suit.diamonds")
        }
    }

    public static func spokenCard(_ value: Int, _ suit: Suit) -> String {
        t("ios.a11y.card", ["rank": spokenRank(value), "suit": spokenSuit(suit)])
    }

    // The seed table. Trimmed to what the app renders today; the generator will
    // supersede it with the full key set from the web (§16.E4). EVERY language
    // carries EVERY key, and that is no longer a promise in a comment:
    // LocalizationTests walks `AppLanguage.allCases` against the English key
    // set, so a missing key fails the suite instead of rendering as its own
    // name on the board.
    private static let table: [String: [String: String]] = [
        "en": [
            "play": "Play", "offline": "Offline", "join_by_code": "Join by code",
            "resume": "Resume game", "replays": "Replays", "tutorial": "Tutorial",
            "settings": "Settings", "about": "About",
            "pass": "Pass", "pickup": "Pickup", "good": "Good", "attack": "Attack", "cover": "Cover",
            "game_over": "Game over", "you_win": "You win", "you_lose": "You are the fool",
            "rematch": "Rematch", "share_replay": "Share replay", "home": "Home",
            "choose_opponent": "Choose opponent", "start_game": "Start game",
            "players": "Players", "thinking": "Thinking…",
            "leave_game_title": "Leave this game?", "leave_game_body": "The game is still live.",
            "leave": "Leave", "cancel": "Cancel",
            "ios.lobby": "Lobby", "ios.game_code": "Game code", "ios.ready": "Ready",
            "ios.add_bot": "Add bot", "ios.share_invite": "Share invite", "join_game": "Join game",
            "ios.dashboard": "Dashboard", "ios.create_game": "Create game", "ios.sign_out": "Sign out",
            "ios.online_soon": "Online play arrives in a later update.",
            "ios.reject": "That move isn’t allowed.",
            "ios.you": "You",
            "ios.fool": "Fool",
            "ios.nobattle": "no battle",
            "ios.msg.yourmove": "Your move",
            "ios.msg.staged": "Move staged - hit Send",
            "ios.msg.waiting": "Waiting for the others",
            "ios.msg.waitingfor": "Waiting for {name}",
            "ios.msg.send": "Send move",
            "ios.msg.sending": "Sending…",
            "ios.msg.undo": "Undo",
            "ios.msg.newgame": "New game",
            "ios.msg.replaylink": "Replay Link",
            "ios.msg.replaylink.copied": "Link copied",
            "ios.msg.pickseat": "Which player are you?",
            "ios.msg.spectating": "Spectating — open the game from your own bubble to play",
            "ios.msg.thread": "A game in this thread",
            "ios.msg.tap": "Durak - tap to play",
            "ios.msg.damaged": "This game can't be opened. The link is damaged, or the game was started under an older version of the rules.",
            "ios.msg.open": "Open the game",
            "ios.msg.fool": "{name} is the fool - tap to watch",
            "ios.msg.isfool": "{name} is the fool",
            "ios.msg.moved": "This game has moved on.",
            "ios.msg.opennewest": "Open the latest",
            "ios.msg.stale": "An older move - the game has moved on",
            "ios.msg.viewanyway": "View this anyway",
            "ios.msg.yourname": "Your name",
            "ios.msg.nameprompt": "What should we call you?",
            "ios.msg.continue": "Continue",
            "ios.msg.seatopen": "Open seat",
            "ios.msg.joinas": "Join as {name}",
            "ios.msg.waitingjoin": "Waiting for {n} more",
            "ios.msg.lobbyfull": "All seats taken",
            "ios.msg.creategame": "Create game",
            // "Start playing", not "Start game" — round-5 m10: the lobby's two
            // buttons read as near-synonyms ("Create game" / "Start game"); the
            // verb keeps them distinct.
            "ios.msg.startgame": "Start playing",
            "ios.msg.gameon": "Foolish - game on! Tap to play",
            "ios.msg.joininvite": "Foolish - tap to join",
            "ios.msg.exitgame": "Leave",
            "ios.msg.left": "{name} left the game",
            "ios.msg.leftanon": "A player left the game",
            "ios.msg.invite": "Send invite",
            "ios.msg.nickname_ph": "your nickname",
            // Round-6 #18: the owner wrote it "Enter Nickname" - Title Case,
            // unlike this file's usual sentence case ("Create game") - so this
            // ONE string breaks the convention on purpose. Leave the rest alone.
            "ios.msg.entername": "Enter Nickname",
            "ios.msg.nametoolong": "nickname too long",
            // 1.0(4): descriptive bubble summaries - the collapsed / notification
            // line describes the move the bubble carries ("Alex attacks with K of
            // ♠"), not a generic "tap to play". The move facts come from the
            // kernel's own evwire (MessageSummary), the words are localized here.
            "ios.msg.cardfmt": "{rank} of {suit}",
            "ios.msg.seatn": "Seat {n}",
            "ios.msg.mv.attack": "{name} attacks with {cards}",
            "ios.msg.mv.pass": "{name} passes {cards}",
            // Round 12: {pairs} is a LIST, not one pair - a bubble can carry a
            // double (or triple) cover, and the caption used to name only the
            // first. `ios.msg.mv.coverpair` is one "beaten with beater"; they
            // join with ", ". A single cover reads exactly as it did before.
            "ios.msg.mv.cover": "{name} covers {pairs}",
            "ios.msg.mv.coverpair": "{target} with {card}",
            "ios.msg.mv.pickup": "{name} took the cards",
            "ios.msg.mv.out": "{name} is out!",
            "ios.msg.mv.good": "{name} says good",
            "ios.msg.mv.nothing": "{name} did nothing",
            "ios.msg.mv.roundover": "Round over - {name} attacks next",
            // The staged-but-unsent reminder under Messages' own Send button
            // (the bobbing blue arrow, MessageTableView.sendHint). ONE short
            // word: it centres under an arrow ~16pt from the screen edge, so a
            // longer phrase runs off the right side (seen with the ru string).
            "ios.msg.sendhint": "Send",
            "ios.msg.started": "{name} started the game - tap to play",
            "ios.msg.joined": "{name} joined - tap to join",
            // 1.0(4): descriptive reject reasons (the plain white flash on the
            // message board). The 21 ENGINE_REJECT_* codes fold into a few clear,
            // non-code-y reasons (FStrings.rejectReason).
            "ios.rej.turn": "It’s not your turn.",
            "ios.rej.pickone": "Pick a card first.",
            "ios.rej.defending": "You’re defending - beat the attack or take it.",
            "ios.rej.notyours": "That card isn’t in your hand.",
            "ios.rej.addrank": "You can only add a rank already on the table.",
            "ios.rej.cover": "That won’t beat it - play higher, or a trump.",
            "ios.rej.capacity": "Too many attacks for the defender’s hand.",
            "ios.rej.passrank": "You can only pass with a matching rank.",
            "ios.rej.mustattack": "The first attacker has to attack.",
            "ios.rej.alreadygood": "You already said good.",
            "ios.rej.notake": "There’s nothing to take.",
            // 1.0(4): the board's left Settings/Help squares + the rules page.
            "ios.help": "Rules",
            "ios.done": "Done",
            "ios.settings.title": "Settings",
            "ios.settings.language": "Language",
            // Round 12: the table material. "Table" heads the section; the two
            // choices name the MATERIAL, not the colour, so a third one later
            // (a red baize, say) reads as a sibling rather than a contradiction.
            "ios.settings.table": "Table",
            "ios.settings.table.wool": "Wool",
            "ios.settings.table.felt": "Green felt",
            "ios.rules.title": "How to play",
            "ios.rules.goal.h": "The goal",
            "ios.rules.goal.b": "The ultimate goal of the game is to get rid of all your cards as soon as possible. Whoever is left with cards at the end is the дурак, or the fool in Russian.",
            "ios.rules.setup.h": "Game setup",
            "ios.rules.setup.b": "If there are four or fewer players, the game is played with only cards 6 through Ace. 2s, 3s, 4s, and 5s are removed from play. Aces are high in this game. Each player is dealt 6 cards, and then one more card is drawn, flipped face up, and placed under the draw pile. The SUIT of this flipped card will indicate the power suit. This power suit is special, and will be explained in defending.",
            "ios.rules.setup.cap": "One card is flipped under the draw pile - its suit is the power suit. Hearts, in every example on this page.",
            "ios.rules.start.h": "Game start",
            "ios.rules.start.b": "Whoever holds the lowest power suit card goes first. In-person games determine this by asking if anyone has a 6, then a 7, and so on. Here, it is done automatically by the game. This person is the first attacker for the round.",
            "ios.rules.sword": "The sword marks the attacker who opens the round.",
            "ios.rules.shield": "The shield marks the defender.",
            "ios.rules.attack.h": "Attacking",
            "ios.rules.attack.b": "The first attacker of a round, indicated by a sword icon, may choose any card or any set of cards that all have the same VALUE in their hand, and place it towards the player to their left (clockwise). That player is now the defender, indicated by a shield icon, and must deal with the attack. To play an attack, tap to select cards and hit the attack button that appears when the selected cards are a valid attack move. Or simply drag cards from your hand to the table.",
            "ios.rules.attack.ok1": "This player may attack with their Queen.",
            "ios.rules.attack.ok2": "They may also attack with both Kings at the same time, as they are the same value.",
            "ios.rules.attack.no1": "They may NOT attack with their 7 and their 10, as they are different values.",
            "ios.rules.defend.h": "Defending",
            "ios.rules.defend.b": "The player currently under attack, indicated by the shield icon, is the defender. There can only be one defender at a time, and all cards placed by other players are cards the defender must deal with. The defender may only cover, pick up, or pass (if allowed). The defender MAY NOT attack themselves. All other players are attackers, and can only attack. Attackers MAY NOT cover any cards on the table.",
            // The same section for a table playing PODKIDNOY. A game without
            // the transfer must not mention it at all (owner) - not even as
            // the "(if allowed)" aside, which only raises a question the rest
            // of the page then refuses to answer.
            "ios.rules.defend.b.nopass": "The player currently under attack, indicated by the shield icon, is the defender. There can only be one defender at a time, and all cards placed by other players are cards the defender must deal with. The defender may only cover or pick up. The defender MAY NOT attack themselves. All other players are attackers, and can only attack. Attackers MAY NOT cover any cards on the table.",
            "ios.rules.cover.h": "Covering",
            "ios.rules.cover.b": "The defender can cover cards on the table by covering each card with either a higher valued card of the same suit, or any power card. This is what makes the power suit special. To cover, select a card and tap the cover button. Alternatively, drag a card in your hand to the card you wish to cover on the table. A common mistake is thinking that a card that is already covered can be further covered by a third card. That is not how the game works. You will never see stacks of three on the table. Think of an attack card as a sword, and a cover card as a shield. The attack is blocked, and thus finished. Only new attacks may be made, in separate piles.",
            "ios.rules.cover.ok1": "A higher card of the same suit covers.",
            "ios.rules.cover.ok2": "Any power card covers any other suit - even a lower value.",
            "ios.rules.cover.no1": "A power attack needs a higher power card - this 7 is too low.",
            "ios.rules.cover.no2": "Higher value, wrong suit - that covers nothing.",
            "ios.rules.throw.h": "Throwing in",
            "ios.rules.throw.b": "As the defender is covering, every other player may \"throw in\" additional attack cards that the defender must additionally cover. The rule for attacking is simple yet can take a while to grasp. If you see the VALUE (such as A, 6, 10) of a card you have on the table, and you are an attacker, you may add that card to the table as a separate new attack. Do not worry about the suits AT ALL. The only limit is the number of cards currently in the defender’s hand. The number of uncovered attacks on the table may not be more than the number of cards the defender holds. Imagine that the defender must be able to match each attack card with a single defense card. If there are too many attack cards, this is physically impossible, and thus not allowed. You may wonder if this could potentially cause the number of attack cards to quickly multiply. You’d be correct, and it is part of the fun of the game. To attack, tap a card or any set of cards where each card in the set has its value appear on the table, and press attack. Or you may drag cards from your hand to the table.",
            "ios.rules.throw.ok1": "A 9 is on the table, so your 9 can go in - suits don’t matter.",
            "ios.rules.throw.ok2": "Both 6s at once - two new attacks.",
            "ios.rules.throw.ok3": "Or the 6 and the 9 together - each value is already out there.",
            "ios.rules.throw.no1": "No 8 and no Jack on the table - nothing to throw in.",
            "ios.rules.throw.no2": "The defender holds one card and one attack is already waiting - no room for another.",
            "ios.rules.pickup.h": "Picking up",
            "ios.rules.pickup.b": "If a defender cannot cover all cards or does not want to cover, they may press the pickup button. This will cause the defender to pick up every card on the table, even if it is already covered. And their turn will be skipped, so the person to their left will start attacking in the next round. So think carefully about choosing to pick up.",
            "ios.rules.pickup.cap": "Pick up here and all three cards go to your hand - the covered pair too.",
            "ios.rules.round.h": "Round end",
            "ios.rules.round.b": "When all cards have been covered and all attackers have agreed to not throw in anymore, all cards on the table go to the discard pile. Players then draw starting from the first attacker, going clockwise through all attackers, drawing cards until they have at least 6 cards. Then the defender draws. This is done automatically by the game. If the deck runs out, then players may start to get rid of their cards and avoid ending up the fool. The round may also end if the defender chooses to pick up. Attacker players then also draw in a similar manner.",
            "ios.rules.pass.h": "Passing",
            "ios.rules.pass.b": "In a game where переводной or \"passing\" is allowed, the defender also has a choice to pass the attack away from them, and to the player on their left. To do this, no card on the table must be covered, and they must have a card of the same VALUE as all the attack cards on the table. Then they may place that card down, and the defender icon will move clockwise to the player on their left. However, similar to how there is a limit on how many cards can be attacked, a pass may not be done if the player to the left has fewer cards than there would be attack cards after the pass. For instance, if there are two attack cards on the table, and the player to the left holds two cards, passing is not possible as passing would result in at least 3 cards on the table (2 + 1 more to pass). This is more than the cards they hold and thus not allowed. To pass, you may tap the card of a matching value and press the pass button. Or drag the card with a matching value to an empty space on the table.",
            "ios.rules.pass.ok1": "An 8 is attacking and you hold an 8 - lay it down and the shield moves on.",
            "ios.rules.pass.no1": "Something is already covered - too late to pass.",
            "ios.rules.pass.no2": "No 8 in your hand - this one is yours to defend.",
            "ios.rules.pass.no3": "Passing would make three attacks, and the next player only holds two cards.",
            "ios.rules.end.h": "Game end",
            "ios.rules.end.b": "Once the draw deck is empty, the game continues playing. If someone gets rid of all their cards they are safe from being the fool. Whoever is the last player still left with cards becomes the fool.",
            // Round-9 (owner): the simpler pre-game rulebook the setup/lobby
            // screens open (RulesView scope .lobby) - how the lobby works, then
            // the goal section above as the quick what-is-this-game.
            "ios.rules.lobby.h": "How the lobby works",
            "ios.rules.lobby.b": "Add your name to join. Once at least two players have joined, anyone can press Start. After the game starts, no one else can join.",
            "ios.rules.variant.h": "Passing",
            "ios.rules.variant.b": "The lobby chooses which Durak this table plays, and the box says which. Ticked is the passing game (perevodnoy): a defender holding a card of the same rank as the attack can put it down and pass the whole attack on to the next player, who now has to defend it. Cleared is the throw-in game (podkidnoy): there is no passing, so a defender either covers every card on the table or picks it all up. Anyone at the table can change it while the lobby is open; once the game starts it is fixed.",
            "ios.rules.fool.h": "The fool pays for it",
            "ios.rules.fool.b": "Normally the lowest power suit card decides who attacks first. There is one exception, and it is the oldest kind of Durak justice: if you press New game after a game ends and the exact same players line up again, the lowest trump decides nothing. The player sitting to the right of the last fool opens instead, which means the fool is the first one attacked. Lose, and the next game comes straight at you. If anyone joins or leaves before Start, the table has changed and the normal rule comes back.",
            "ios.lobby.passing": "Passing",
            "ios.rules.lbl.table": "on the table",
            "ios.rules.lbl.hand": "your hand",
            "ios.rules.defender": "Defender",
            "ios.rules.nextplayer": "Next player",
            "ios.msg.nametaken": "name taken in this game",
            "ios.a11y.attackfirst": "You attack first",
            "ios.a11y.on": "on", "ios.a11y.off": "off",
            "ios.a11y.defending": "Defending",
            "ios.a11y.attacking": "attacking",
            "ios.a11y.saidgood": "said good",
            "ios.a11y.thinking": "thinking",
            "ios.a11y.out": "out of the game",
            "ios.a11y.cards": "{n} cards",
            "ios.a11y.deck": "{n} cards left in the deck",
            "ios.a11y.trump": "trump {suit}",
            "ios.a11y.trumpmark": "trump",
            "ios.a11y.discard": "{n} cards discarded",
            "ios.a11y.covered": "{attack}, covered by {defense}",
            "ios.a11y.uncovered": "{attack}, uncovered",
            "ios.a11y.hiddencard": "hidden card",
            "ios.a11y.facedown": "face down card",
            "ios.a11y.card": "{rank} of {suit}",
            "ios.suit.spades": "spades", "ios.suit.hearts": "hearts",
            "ios.suit.clubs": "clubs", "ios.suit.diamonds": "diamonds",
            "ios.rank.ace": "ace", "ios.rank.king": "king",
            "ios.rank.queen": "queen", "ios.rank.jack": "jack", "ios.rank.ten": "ten",
            "ios.tut_next": "Got it",
            "ios.tut_done": "Start playing",
            "ios.tut_1": "Welcome to Durak. The lowest card of the trump suit decides who attacks first. Trump beats every other suit.",
            "ios.tut_2": "To attack, tap a card in your hand. Your opponent must beat it - or pick it all up.",
            "ios.tut_3": "To defend, tap one of your cards, then tap the attack it beats. A higher card of the same suit, or any trump, covers it.",
            "ios.tut_4": "Can’t or won’t defend? Tap Pickup to pick up the cards. Finished attacking? Tap Done.",
            "ios.tut_5": "Empty your hand before everyone else. The last player holding cards is the fool. Good luck!",
            "ios.bot.random": "Miami", "ios.bot.handwritten": "New York",
            "ios.bot.robusta": "Seoul", "ios.bot.firecracker": "Madrid",
            "ios.bot.blackpowder": "Vienna", "ios.bot.cordite": "St. Petersburg",
            "ios.bot.octogen": "Moscow",
            "ios.bot.max": "Max", "ios.bot.km": "{km} km from Moscow",
            "ios.bot.km0": "The Kremlin itself",
        ],
        "ru": [
            "play": "Играть", "offline": "Оффлайн", "join_by_code": "Войти по коду",
            "resume": "Продолжить игру", "replays": "Записи", "tutorial": "Обучение",
            "settings": "Настройки", "about": "О приложении",
            "pass": "Пас", "pickup": "Взять", "good": "Бито", "attack": "Атака", "cover": "Крыть",
            "game_over": "Игра окончена", "you_win": "Вы выиграли", "you_lose": "Вы дурак",
            "rematch": "Ещё раз", "share_replay": "Поделиться записью", "home": "Домой",
            "choose_opponent": "Выберите соперника", "start_game": "Начать игру",
            "players": "Игроки", "thinking": "Думает…",
            "leave_game_title": "Выйти из игры?", "leave_game_body": "Игра ещё идёт.",
            "leave": "Выйти", "cancel": "Отмена",
            "ios.lobby": "Лобби", "ios.game_code": "Код игры", "ios.ready": "Готов",
            "ios.add_bot": "Добавить бота", "ios.share_invite": "Поделиться", "join_game": "Войти",
            "ios.dashboard": "Панель", "ios.create_game": "Создать игру", "ios.sign_out": "Выйти",
            "ios.online_soon": "Онлайн-игра появится в следующем обновлении.",
            "ios.reject": "Такой ход недопустим.",
            "ios.you": "Вы",
            "ios.fool": "Дурак",
            "ios.nobattle": "нет боя",
            "ios.msg.yourmove": "Ваш ход",
            "ios.msg.staged": "Ход готов - нажмите «Отправить»",
            "ios.msg.waiting": "Ждём других игроков",
            "ios.msg.waitingfor": "Ждём: {name}",
            "ios.msg.send": "Отправить ход",
            "ios.msg.sending": "Отправка…",
            "ios.msg.undo": "Отменить",
            "ios.msg.newgame": "Новая игра",
            "ios.msg.replaylink": "Ссылка на повтор",
            "ios.msg.replaylink.copied": "Ссылка скопирована",
            "ios.msg.pickseat": "Кто вы из игроков?",
            "ios.msg.spectating": "Вы наблюдаете — чтобы играть, откройте игру из своего сообщения",
            "ios.msg.thread": "Игра в этой переписке",
            "ios.msg.tap": "Дурак - нажмите, чтобы играть",
            "ios.msg.damaged": "Игру не открыть. Ссылка повреждена - или игра была начата по старой версии правил.",
            "ios.msg.open": "Открыть игру",
            "ios.msg.fool": "{name} - дурак - нажмите, чтобы посмотреть",
            "ios.msg.isfool": "{name} - дурак",
            "ios.msg.moved": "Игра ушла вперёд.",
            "ios.msg.opennewest": "Открыть последнее",
            "ios.msg.stale": "Старый ход - игра уже ушла вперёд",
            "ios.msg.viewanyway": "Всё равно посмотреть",
            "ios.msg.yourname": "Ваше имя",
            "ios.msg.nameprompt": "Как вас называть?",
            "ios.msg.continue": "Продолжить",
            "ios.msg.seatopen": "Свободное место",
            "ios.msg.joinas": "Войти как {name}",
            "ios.msg.waitingjoin": "Ждём ещё: {n}",
            "ios.msg.lobbyfull": "Все места заняты",
            "ios.msg.creategame": "Создать игру",
            "ios.msg.startgame": "Начать играть",
            "ios.msg.gameon": "Дурак - игра началась! Нажмите, чтобы играть",
            "ios.msg.joininvite": "Дурак - нажмите, чтобы присоединиться",
            "ios.msg.exitgame": "Выйти",
            "ios.msg.left": "{name} вышел из игры",
            "ios.msg.leftanon": "Игрок вышел из игры",
            "ios.msg.invite": "Отправить приглашение",
            "ios.msg.nickname_ph": "ваш ник",
            // Round-6 #18: capitalised to match the English "Enter Nickname" -
            // only the first letter, per Russian convention (title-casing every
            // word would be wrong here).
            "ios.msg.entername": "Введите ник",
            "ios.msg.nametoolong": "слишком длинный ник",
            "ios.msg.cardfmt": "{rank} {suit}",
            "ios.msg.seatn": "Игрок {n}",
            "ios.msg.mv.attack": "{name} атакует: {cards}",
            "ios.msg.mv.pass": "{name} переводит: {cards}",
            "ios.msg.mv.cover": "{name} кроет {pairs}",
            "ios.msg.mv.coverpair": "{target}: {card}",
            "ios.msg.mv.pickup": "{name} забирает карты",
            "ios.msg.mv.out": "{name} вышел!",
            "ios.msg.mv.good": "{name} говорит: бито",
            "ios.msg.mv.nothing": "{name} ничего не сделал",
            "ios.msg.mv.roundover": "Раунд окончен - атакует {name}",
            "ios.msg.sendhint": "Отправь",
            "ios.msg.started": "{name} начал игру - нажмите, чтобы играть",
            "ios.msg.joined": "{name} присоединился - нажмите, чтобы войти",
            "ios.rej.turn": "Сейчас не ваш ход.",
            "ios.rej.pickone": "Сначала выберите карту.",
            "ios.rej.defending": "Вы защищаетесь - побейте атаку или возьмите.",
            "ios.rej.notyours": "Этой карты нет в вашей руке.",
            "ios.rej.addrank": "Подкинуть можно только карту достоинства, что уже на столе.",
            "ios.rej.cover": "Так не побить - сыграйте старше или козырем.",
            "ios.rej.capacity": "Слишком много карт для руки защищающегося.",
            "ios.rej.passrank": "Переводить можно только картой того же достоинства.",
            "ios.rej.mustattack": "Первый игрок должен атаковать.",
            "ios.rej.alreadygood": "Вы уже сказали «бито».",
            "ios.rej.notake": "Брать нечего.",
            "ios.help": "Правила",
            "ios.done": "Готово",
            "ios.settings.title": "Настройки",
            "ios.settings.language": "Язык",
            "ios.settings.table": "Стол",
            "ios.settings.table.wool": "Шерсть",
            "ios.settings.table.felt": "Зелёное сукно",
            "ios.rules.title": "Как играть",
            "ios.rules.goal.h": "Цель игры",
            "ios.rules.goal.b": "Главная цель - как можно скорее избавиться от всех своих карт. Кто остался с картами в конце, тот и есть дурак.",
            "ios.rules.setup.h": "Подготовка",
            "ios.rules.setup.b": "Если игроков четверо или меньше, играют картами от шестёрки до туза - двойки, тройки, четвёрки и пятёрки убирают из игры. Туз - старшая карта. Каждому сдают по шесть карт, затем ещё одну открывают и кладут под колоду. МАСТЬ этой карты - козырная. Козырь особенный, об этом - в защите.",
            "ios.rules.setup.cap": "Одну карту открывают и кладут под колоду - её масть и есть козырь. Во всех примерах на этой странице козыри червы.",
            "ios.rules.start.h": "Начало игры",
            "ios.rules.start.b": "Первым ходит тот, у кого младший козырь. Вживую это выясняют вопросами - у кого шестёрка? а семёрка? - здесь игра определяет это сама. Этот игрок - первый атакующий раунда.",
            "ios.rules.sword": "Меч - атакующий, который открывает раунд.",
            "ios.rules.shield": "Щит - защитник.",
            "ios.rules.attack.h": "Атака",
            "ios.rules.attack.b": "Первый атакующий может выложить любую карту - или несколько карт ОДНОГО достоинства - в сторону игрока слева (по часовой). Тот становится защитником и должен разобраться с атакой. Коснитесь карт, чтобы выбрать их, и нажмите «Атака», когда выбор складывается в допустимый ход, - или просто перетащите карты из руки на стол.",
            "ios.rules.attack.ok1": "Дама сама по себе - отличная атака.",
            "ios.rules.attack.ok2": "Или оба короля разом - достоинство одно.",
            "ios.rules.attack.no1": "Но не семёрка с десяткой вместе - достоинства разные.",
            "ios.rules.defend.h": "Защита",
            "ios.rules.defend.b": "Защитник всегда один, и все карты, выложенные остальными, - его забота. Защитник может только крыть, взять или перевести (если перевод разрешён) - сам он не атакует. Все остальные - атакующие, и крыть они не могут.",
            "ios.rules.defend.b.nopass": "Защитник всегда один, и все карты, выложенные остальными, - его забота. Защитник может только крыть или взять - сам он не атакует. Все остальные - атакующие, и крыть они не могут.",
            "ios.rules.cover.h": "Крыть",
            "ios.rules.cover.b": "Защитник кроет каждую карту атаки старшей картой той же масти - или ЛЮБЫМ козырем: в этом и сила козырной масти. Выберите карту и нажмите «Крыть» или перетащите её на карту, которую хотите покрыть. Частая ошибка: уже покрытую карту нельзя покрыть ещё раз - стопок из трёх карт не бывает. Атака - меч, покрытие - щит: отбитая атака кончена. Новые атаки кладутся отдельными стопками.",
            "ios.rules.cover.ok1": "Кроет старшая карта той же масти.",
            "ios.rules.cover.ok2": "Любой козырь кроет любую другую масть - даже младший.",
            "ios.rules.cover.no1": "Козырную атаку бьёт только старший козырь - эта семёрка мала.",
            "ios.rules.cover.no2": "Старше, но не той масти - ничего не кроет.",
            "ios.rules.throw.h": "Подкидывание",
            "ios.rules.throw.b": "Пока защитник отбивается, остальные могут подкидывать. Правило простое, но к нему привыкают: если ДОСТОИНСТВО карты из вашей руки (например, туз, шестёрка, десятка) уже есть где-то на столе, её можно подкинуть как новую отдельную атаку. О мастях не думайте ВООБЩЕ. Ограничение одно - рука защитника: непокрытых атак не может быть больше, чем у него карт, - на каждую атаку он должен суметь ответить картой. Если атак слишком много, это физически невозможно, а значит нельзя. Может показаться, что так стол разрастается стремительно. Так и есть - и в этом часть азарта. Чтобы подкинуть, коснитесь карты или карт, достоинство каждой из которых уже есть на столе, и нажмите «Атака». Или перетащите карты из руки на стол.",
            "ios.rules.throw.ok1": "Девятка есть на столе - значит, ваша девятка идёт в ход, масть не важна.",
            "ios.rules.throw.ok2": "Обе шестёрки разом - две новые атаки.",
            "ios.rules.throw.ok3": "Или шестёрка с девяткой вместе - оба достоинства уже на столе.",
            "ios.rules.throw.no1": "Ни восьмёрки, ни валета на столе - подкинуть нечего.",
            "ios.rules.throw.no2": "У защитника одна карта, и одна атака уже ждёт - больше некуда.",
            "ios.rules.pickup.h": "Взять",
            "ios.rules.pickup.b": "Если защитник не может покрыть всё - или не хочет - он нажимает «Взять» и забирает в руку ВСЕ карты со стола, включая уже покрытые. Его ход пропускается: следующий раунд открывает игрок слева. Так что брать или нет - решайте с умом.",
            "ios.rules.pickup.cap": "Возьмёте здесь - и все три карты уйдут в руку, покрытая пара тоже.",
            "ios.rules.round.h": "Конец раунда",
            "ios.rules.round.b": "Когда все атаки покрыты и никто больше не подкидывает, карты со стола уходят в отбой - они выбыли из игры. Затем все добирают до шести карт: сначала первый атакующий, за ним остальные атакующие по часовой, защитник - последним. Игра делает это сама. Если защитник взял, раунд кончается так же, и добор тот же. Когда колода опустела, играют тем, что на руках.",
            "ios.rules.pass.h": "Перевод",
            "ios.rules.pass.b": "В игре с переводом у защитника есть ещё один выход: перевести атаку дальше. Если на столе ещё ничего не покрыто и у вас есть карта ТОГО ЖЕ достоинства, что и карты атаки, положите её - и щит перейдёт к игроку слева от вас. Ограничение знакомое: перевести нельзя, если у следующего игрока меньше карт, чем станет атак после перевода. Например: на столе две карты атаки, а игрок слева держит две карты - переводить нельзя, ведь после перевода на столе будет минимум три карты (2 + 1 переводная), а это больше, чем у него в руке. Коснитесь подходящей карты и нажмите «Пас» - или перетащите её на свободное место стола.",
            "ios.rules.pass.ok1": "Атакуют восьмёркой, и у вас есть восьмёрка - кладите, щит двинется дальше.",
            "ios.rules.pass.no1": "Что-то уже покрыто - переводить поздно.",
            "ios.rules.pass.no2": "Восьмёрки в руке нет - эта атака ваша.",
            "ios.rules.pass.no3": "После перевода атак станет три, а у следующего игрока всего две карты.",
            "ios.rules.end.h": "Конец игры",
            "ios.rules.end.b": "Когда колода пуста, игра продолжается. Избавились от карт - вы в безопасности. Последний, кто остался с картами, - дурак.",
            "ios.rules.lobby.h": "Как работает лобби",
            "ios.rules.lobby.b": "Введите имя, чтобы присоединиться. Когда есть хотя бы два игрока, любой может нажать «Начать». После начала игры присоединиться уже нельзя.",
            "ios.rules.variant.h": "Переводной",
            "ios.rules.variant.b": "В лобби выбирают, в какого дурака играет этот стол, и галочка говорит, в какого. Галочка стоит - играем в переводного: защищающийся с картой того же достоинства, что и атака, может положить её и перевести всю атаку на следующего игрока, и отбиваться теперь ему. Галочки нет - играем в подкидного: перевода нет, защищающийся либо кроет всё, что на столе, либо забирает. Пока лобби открыто, поменять может любой за столом; после начала игры правило зафиксировано.",
            "ios.rules.fool.h": "Дурак платит",
            "ios.rules.fool.b": "Обычно первым ходит тот, у кого младший козырь. Есть одно исключение, и это самая старая дурацкая справедливость: если после конца игры нажать «Новая игра» и за стол сядут ровно те же игроки, младший козырь не решает ничего. Первым ходит сосед справа от прошлого дурака - то есть по дураку и бьют первым. Проиграл - и следующая игра идёт прямо на тебя. Если до старта кто-то войдёт или выйдет, стол уже другой, и обычное правило возвращается.",
            "ios.lobby.passing": "Переводной",
            "ios.rules.lbl.table": "на столе",
            "ios.rules.lbl.hand": "ваша рука",
            "ios.rules.defender": "Защитник",
            "ios.rules.nextplayer": "Следующий игрок",
            "ios.msg.nametaken": "ник уже занят в этой игре",
            "ios.a11y.attackfirst": "Вы ходите первым",
            "ios.a11y.on": "включено", "ios.a11y.off": "выключено",
            "ios.a11y.defending": "Защищается",
            "ios.a11y.attacking": "атакует",
            "ios.a11y.saidgood": "сказал бито",
            "ios.a11y.thinking": "думает",
            "ios.a11y.out": "вышел из игры",
            "ios.a11y.cards": "карт: {n}",
            "ios.a11y.deck": "карт в колоде: {n}",
            "ios.a11y.trump": "козырь: {suit}",
            "ios.a11y.trumpmark": "козырь",
            "ios.a11y.discard": "карт в отбое: {n}",
            "ios.a11y.covered": "{attack}, покрыта: {defense}",
            "ios.a11y.uncovered": "{attack}, не покрыта",
            "ios.a11y.hiddencard": "закрытая карта",
            "ios.a11y.facedown": "карта рубашкой вверх",
            "ios.a11y.card": "{rank}, {suit}",
            "ios.suit.spades": "пики", "ios.suit.hearts": "черви",
            "ios.suit.clubs": "трефы", "ios.suit.diamonds": "бубны",
            "ios.rank.ace": "туз", "ios.rank.king": "король",
            "ios.rank.queen": "дама", "ios.rank.jack": "валет", "ios.rank.ten": "десятка",
            "ios.tut_next": "Понятно",
            "ios.tut_done": "Начать игру",
            "ios.tut_1": "Добро пожаловать в Дурак. Младшая козырная карта определяет, кто атакует первым. Козырь бьёт любую другую масть.",
            "ios.tut_2": "Чтобы атаковать, коснитесь карты в руке. Соперник должен её побить - или взять всё.",
            "ios.tut_3": "Чтобы защищаться, коснитесь своей карты, затем атаки, которую она бьёт. Побить можно старшей картой той же масти или козырем.",
            "ios.tut_4": "Не можете или не хотите защищаться? Нажмите «Взять». Закончили атаку? Нажмите «Бито».",
            "ios.tut_5": "Избавьтесь от карт раньше всех. Последний с картами - дурак. Удачи!",
            "ios.bot.random": "Майами", "ios.bot.handwritten": "Нью-Йорк",
            "ios.bot.robusta": "Сеул", "ios.bot.firecracker": "Мадрид",
            "ios.bot.blackpowder": "Вена", "ios.bot.cordite": "Петербург",
            "ios.bot.octogen": "Москва",
            "ios.bot.max": "Макс", "ios.bot.km": "{km} км от Москвы",
            "ios.bot.km0": "Сам Кремль",
        ],
        "ko": [
            "play": "플레이", "offline": "오프라인", "join_by_code": "코드로 참가",
            "resume": "게임 계속하기", "replays": "리플레이", "tutorial": "튜토리얼",
            "settings": "설정", "about": "정보",
            "pass": "패스", "pickup": "가져오기", "good": "완료", "attack": "공격", "cover": "방어",
            "game_over": "게임 종료", "you_win": "승리", "you_lose": "당신이 바보입니다",
            "rematch": "재대결", "share_replay": "리플레이 공유", "home": "홈",
            "choose_opponent": "상대 선택", "start_game": "게임 시작",
            "players": "플레이어", "thinking": "생각 중…",
            "leave_game_title": "게임을 나갈까요?", "leave_game_body": "게임이 아직 진행 중입니다.",
            "leave": "나가기", "cancel": "취소",
            "ios.lobby": "로비", "ios.game_code": "게임 코드", "ios.ready": "준비",
            "ios.add_bot": "봇 추가", "ios.share_invite": "초대 공유", "join_game": "참가",
            "ios.dashboard": "대시보드", "ios.create_game": "게임 만들기", "ios.sign_out": "로그아웃",
            "ios.online_soon": "온라인 플레이는 다음 업데이트에서 제공됩니다.",
            "ios.reject": "허용되지 않는 수입니다.",
            "ios.you": "나",
            "ios.fool": "바보",
            "ios.nobattle": "전투 없음",
            "ios.msg.yourmove": "당신 차례",
            "ios.msg.staged": "수 준비됨 - 전송하세요",
            "ios.msg.waiting": "다른 플레이어 대기 중",
            "ios.msg.waitingfor": "{name} 대기 중",
            "ios.msg.send": "수 보내기",
            "ios.msg.sending": "보내는 중…",
            "ios.msg.undo": "취소",
            "ios.msg.newgame": "새 게임",
            "ios.msg.replaylink": "다시보기 링크",
            "ios.msg.replaylink.copied": "링크 복사됨",
            "ios.msg.pickseat": "당신은 어느 플레이어인가요?",
            "ios.msg.spectating": "관전 중 — 플레이하려면 내 말풍선에서 게임을 여세요",
            "ios.msg.thread": "이 대화의 게임",
            "ios.msg.tap": "두락 - 탭하여 플레이",
            "ios.msg.damaged": "게임을 열 수 없습니다. 링크가 손상되었거나, 이전 버전의 규칙으로 시작된 게임입니다.",
            "ios.msg.open": "게임 열기",
            "ios.msg.fool": "{name}이(가) 바보입니다 - 탭하여 보기",
            "ios.msg.isfool": "{name}이(가) 바보입니다",
            "ios.msg.moved": "이 게임은 이미 진행되었습니다.",
            "ios.msg.opennewest": "최신 상태 열기",
            "ios.msg.stale": "이전 수 - 게임이 이미 진행되었습니다",
            "ios.msg.viewanyway": "그래도 이 상태 보기",
            "ios.msg.yourname": "이름",
            "ios.msg.nameprompt": "이름을 알려주세요",
            "ios.msg.continue": "계속",
            "ios.msg.seatopen": "빈 자리",
            "ios.msg.joinas": "{name}(으)로 참가",
            "ios.msg.waitingjoin": "{n}명 더 기다리는 중",
            "ios.msg.lobbyfull": "모든 자리가 찼습니다",
            "ios.msg.creategame": "게임 만들기",
            "ios.msg.startgame": "플레이 시작",
            "ios.msg.gameon": "두락 - 게임 시작! 탭하여 플레이",
            "ios.msg.joininvite": "두락 - 탭하여 참가",
            "ios.msg.exitgame": "나가기",
            "ios.msg.left": "{name} 님이 게임을 떠났습니다",
            "ios.msg.leftanon": "한 명이 게임을 떠났습니다",
            "ios.msg.invite": "초대 보내기",
            "ios.msg.nickname_ph": "닉네임",
            "ios.msg.entername": "닉네임을 입력하세요",
            "ios.msg.nametoolong": "닉네임이 너무 깁니다",
            "ios.msg.cardfmt": "{rank} {suit}",
            "ios.msg.seatn": "{n}번 자리",
            "ios.msg.mv.attack": "{name} 공격: {cards}",
            "ios.msg.mv.pass": "{name} 넘김: {cards}",
            "ios.msg.mv.cover": "{name} 방어: {pairs}",
            "ios.msg.mv.coverpair": "{target}→{card}",
            "ios.msg.mv.pickup": "{name} 카드 가져감",
            "ios.msg.mv.out": "{name} 탈락!",
            "ios.msg.mv.good": "{name} 완료 선언",
            "ios.msg.mv.nothing": "{name} 아무것도 하지 않았습니다",
            "ios.msg.mv.roundover": "라운드 종료 - 다음 공격: {name}",
            "ios.msg.sendhint": "보내기",
            "ios.msg.started": "{name} 게임 시작 - 탭하여 플레이",
            "ios.msg.joined": "{name} 참가 - 탭하여 참가",
            "ios.rej.turn": "당신 차례가 아닙니다.",
            "ios.rej.pickone": "먼저 카드를 선택하세요.",
            "ios.rej.defending": "방어 중입니다 - 공격을 막거나 가져오세요.",
            "ios.rej.notyours": "그 카드는 손패에 없습니다.",
            "ios.rej.addrank": "테이블에 이미 있는 숫자만 추가할 수 있습니다.",
            "ios.rej.cover": "그걸로는 못 이깁니다 - 더 높거나 으뜸패를 내세요.",
            "ios.rej.capacity": "방어자 손패에 비해 공격이 너무 많습니다.",
            "ios.rej.passrank": "같은 숫자로만 넘길 수 있습니다.",
            "ios.rej.mustattack": "첫 공격자는 공격해야 합니다.",
            "ios.rej.alreadygood": "이미 완료를 선언했습니다.",
            "ios.rej.notake": "가져올 카드가 없습니다.",
            "ios.help": "규칙",
            "ios.done": "완료",
            "ios.settings.title": "설정",
            "ios.settings.language": "언어",
            "ios.settings.table": "테이블",
            "ios.settings.table.wool": "울",
            "ios.settings.table.felt": "그린 펠트",
            "ios.rules.title": "게임 방법",
            "ios.rules.goal.h": "게임의 목표",
            "ios.rules.goal.b": "궁극의 목표는 손의 카드를 최대한 빨리 없애는 것입니다. 끝까지 카드를 들고 있는 사람이 дурак - 러시아어로 ‘바보’입니다.",
            "ios.rules.setup.h": "게임 준비",
            "ios.rules.setup.b": "플레이어가 네 명 이하면 6부터 에이스까지의 카드만 씁니다 - 2, 3, 4, 5는 뺍니다. 에이스가 가장 높습니다. 각자 여섯 장을 받은 뒤, 카드 한 장을 더 뽑아 앞면으로 뒤집어 뽑을 더미 아래에 둡니다. 그 카드의 무늬가 으뜸 무늬입니다. 으뜸 무늬는 특별하며, ‘수비’에서 설명합니다.",
            "ios.rules.setup.cap": "뽑을 더미 아래에 카드 한 장을 뒤집어 둡니다 - 그 무늬가 으뜸 무늬입니다. 이 페이지의 모든 예시는 하트입니다.",
            "ios.rules.start.h": "게임 시작",
            "ios.rules.start.b": "가장 낮은 으뜸 무늬 카드를 든 사람이 먼저 합니다. 실제 게임에서는 6 있나요? 7은요? 하고 물어 가며 정하지만, 여기서는 게임이 자동으로 정합니다. 그 사람이 이번 라운드의 첫 공격자입니다.",
            "ios.rules.sword": "검은 라운드를 여는 공격자를 나타냅니다.",
            "ios.rules.shield": "방패는 방어자를 나타냅니다.",
            "ios.rules.attack.h": "공격",
            "ios.rules.attack.b": "첫 공격자는 아무 카드 한 장, 또는 값이 같은 카드 여러 장을 왼쪽(시계 방향) 플레이어 쪽으로 낼 수 있습니다. 그 플레이어가 방어자가 되어 공격을 처리해야 합니다. 카드를 탭해 고르고, 유효한 공격이 되면 나타나는 공격 버튼을 누르세요 - 아니면 손에서 테이블로 끌어다 놓아도 됩니다.",
            "ios.rules.attack.ok1": "퀸 한 장으로도 훌륭한 공격입니다.",
            "ios.rules.attack.ok2": "킹 두 장을 한꺼번에 - 값이 같으니까요.",
            "ios.rules.attack.no1": "7과 10을 같이는 안 됩니다 - 값이 다릅니다.",
            "ios.rules.defend.h": "수비",
            "ios.rules.defend.b": "방어자는 한 번에 한 명뿐이고, 다른 플레이어들이 낸 카드는 전부 방어자의 몫입니다. 방어자는 막기, 가져오기, 넘기기(허용된 경우)만 할 수 있고 - 스스로 공격할 수는 없습니다. 나머지는 모두 공격자이며, 공격자는 막을 수 없습니다.",
            "ios.rules.defend.b.nopass": "방어자는 한 번에 한 명뿐이고, 다른 플레이어들이 낸 카드는 전부 방어자의 몫입니다. 방어자는 막기와 가져오기만 할 수 있고 - 스스로 공격할 수는 없습니다. 나머지는 모두 공격자이며, 공격자는 막을 수 없습니다.",
            "ios.rules.cover.h": "막기",
            "ios.rules.cover.b": "방어자는 각 공격 카드를 같은 무늬의 더 높은 카드, 또는 아무 으뜸패로나 막습니다 - 이것이 으뜸 무늬의 힘입니다. 카드를 선택하고 방어 버튼을 누르거나, 막고 싶은 카드 위로 끌어다 놓으세요. 흔한 오해 하나: 이미 막힌 카드는 다시 막을 수 없습니다 - 석 장짜리 더미는 없습니다. 공격은 검, 막은 카드는 방패입니다: 막힌 공격은 끝난 것입니다. 새 공격은 새 더미로 놓입니다.",
            "ios.rules.cover.ok1": "같은 무늬의 더 높은 카드로 막습니다.",
            "ios.rules.cover.ok2": "으뜸패는 값이 낮아도 다른 무늬를 다 막습니다.",
            "ios.rules.cover.no1": "으뜸패 공격은 더 높은 으뜸패로만 - 이 7은 낮습니다.",
            "ios.rules.cover.no2": "값은 높아도 무늬가 다르면 못 막습니다.",
            "ios.rules.throw.h": "추가 공격",
            "ios.rules.throw.b": "방어자가 막는 동안 다른 플레이어들은 공격을 더 던져 넣을 수 있습니다. 규칙은 간단하지만 익숙해지는 데 시간이 좀 걸립니다: 손에 든 카드의 값(예: A, 6, 10)이 테이블 위 어디든 이미 있다면, 그 카드를 새로운 별도의 공격으로 낼 수 있습니다. 무늬는 전혀 신경 쓰지 마세요. 한도는 방어자의 손 하나뿐입니다: 막지 않은 공격 수가 방어자가 든 카드 수를 넘을 수 없습니다 - 공격마다 카드 한 장으로 답할 수 있어야 하니까요. 공격이 너무 많으면 물리적으로 불가능하니 허용되지 않습니다. 이러면 테이블이 순식간에 불어나지 않을까요? 맞습니다. 그게 이 게임의 재미입니다. 던져 넣으려면 값이 테이블에 이미 있는 카드들을 탭하고 공격을 누르거나, 손에서 테이블로 끌어다 놓으세요.",
            "ios.rules.throw.ok1": "테이블에 9가 있으니 당신의 9를 낼 수 있습니다 - 무늬는 상관없습니다.",
            "ios.rules.throw.ok2": "6 두 장을 한꺼번에 - 새 공격 둘.",
            "ios.rules.throw.ok3": "6과 9를 같이 - 두 값 모두 이미 나와 있습니다.",
            "ios.rules.throw.no1": "테이블에 8도 잭도 없으니 던질 게 없습니다.",
            "ios.rules.throw.no2": "방어자 손엔 한 장, 이미 공격 하나가 기다립니다 - 더는 안 됩니다.",
            "ios.rules.pickup.h": "가져오기",
            "ios.rules.pickup.b": "다 막을 수 없거나 막고 싶지 않다면, 방어자는 가져오기 버튼을 누릅니다. 그러면 테이블의 모든 카드를 - 이미 막힌 것까지 - 손에 가져오고, 다음 차례를 건너뜁니다: 다음 라운드는 왼쪽 플레이어가 엽니다. 그러니 가져올지는 신중히 정하세요.",
            "ios.rules.pickup.cap": "여기서 가져오면 석 장 모두 - 막힌 쌍까지 - 손에 들어옵니다.",
            "ios.rules.round.h": "라운드 종료",
            "ios.rules.round.b": "모든 공격이 막히고 공격자들이 더 던지지 않기로 하면, 테이블의 카드는 전부 버린 더미로 갑니다. 그리고 모두 여섯 장이 될 때까지 뽑습니다 - 첫 공격자부터, 나머지 공격자들이 시계 방향으로, 방어자가 마지막. 게임이 자동으로 처리합니다. 방어자가 가져와도 라운드는 같은 방식으로 끝나고, 뽑기도 같습니다. 뽑을 더미가 비면 손에 든 카드로 승부합니다.",
            "ios.rules.pass.h": "넘기기",
            "ios.rules.pass.b": "переводной - ‘넘기기’가 허용된 게임에서는 방어자에게 선택지가 하나 더 있습니다: 공격을 옆으로 넘기는 것. 테이블에 막힌 카드가 하나도 없고, 공격 카드들과 같은 값의 카드를 들고 있다면, 그 카드를 내려놓으세요 - 방패가 왼쪽 플레이어에게 넘어갑니다. 익숙한 한도가 그대로 적용됩니다: 넘긴 뒤의 공격 수가 다음 플레이어의 카드 수보다 많아지면 넘길 수 없습니다. 예를 들어 테이블에 공격 카드가 두 장이고 왼쪽 플레이어가 두 장만 들고 있다면, 넘기면 테이블에 최소 석 장(2 + 넘기는 1장)이 되어 그가 든 카드보다 많아지므로 안 됩니다. 값이 맞는 카드를 탭하고 패스를 누르거나, 테이블의 빈자리로 끌어다 놓으세요.",
            "ios.rules.pass.ok1": "8이 공격 중인데 8을 들고 있다면 - 내려놓으세요, 방패가 넘어갑니다.",
            "ios.rules.pass.no1": "이미 막힌 카드가 있으면 - 넘기기엔 늦었습니다.",
            "ios.rules.pass.no2": "손에 8이 없으니 - 이번엔 직접 막아야 합니다.",
            "ios.rules.pass.no3": "넘기면 공격이 셋, 다음 플레이어 카드는 두 장뿐입니다.",
            "ios.rules.end.h": "게임 종료",
            "ios.rules.end.b": "뽑을 더미가 비어도 게임은 계속됩니다. 손을 다 비우면 바보가 될 일은 없습니다. 마지막까지 카드를 들고 있는 사람이 바보입니다.",
            "ios.rules.lobby.h": "로비 안내",
            "ios.rules.lobby.b": "이름을 입력해 참가하세요. 두 명 이상 모이면 누구나 시작을 누를 수 있습니다. 게임이 시작되면 더 이상 참가할 수 없습니다.",
            "ios.rules.variant.h": "넘기기",
            "ios.rules.variant.b": "이 테이블이 어떤 두라크를 하는지는 로비에서 정하며, 체크 상자가 그것을 알려줍니다. 체크되어 있으면 넘기기 게임(페레보드노이)입니다. 수비수가 공격 카드와 같은 숫자의 카드를 가지고 있으면 그것을 내려놓고 공격 전체를 다음 사람에게 넘길 수 있고, 이제 그 사람이 막아야 합니다. 체크가 없으면 던지기 게임(포드키드노이)입니다. 넘기기가 없으므로 수비수는 테이블 위의 모든 카드를 막거나 전부 가져가야 합니다. 로비가 열려 있는 동안에는 테이블에 앉은 누구나 바꿀 수 있고, 게임이 시작되면 고정됩니다.",
            "ios.rules.fool.h": "바보가 값을 치른다",
            "ios.rules.fool.b": "보통은 가장 낮은 으뜸패를 가진 사람이 먼저 공격합니다. 예외가 하나 있는데, 두라크에서 가장 오래된 방식의 정의입니다. 게임이 끝난 뒤 새 게임을 누르고 똑같은 사람들이 다시 앉으면 낮은 으뜸패는 아무것도 결정하지 않습니다. 지난 판 바보의 오른쪽에 앉은 사람이 먼저 공격하고, 따라서 바보가 가장 먼저 공격을 받습니다. 지면 다음 판이 바로 당신에게 옵니다. 시작 전에 누군가 들어오거나 나가면 판이 달라진 것이므로 원래 규칙으로 돌아갑니다.",
            "ios.lobby.passing": "넘기기",
            "ios.rules.lbl.table": "테이블",
            "ios.rules.lbl.hand": "내 손",
            "ios.rules.defender": "방어자",
            "ios.rules.nextplayer": "다음 플레이어",
            "ios.msg.nametaken": "이미 사용 중인 닉네임입니다",
            "ios.a11y.attackfirst": "당신이 먼저 공격합니다",
            "ios.a11y.on": "켬", "ios.a11y.off": "끔",
            "ios.a11y.defending": "방어 중",
            "ios.a11y.attacking": "공격 중",
            "ios.a11y.saidgood": "완료 선언",
            "ios.a11y.thinking": "생각 중",
            "ios.a11y.out": "탈락",
            "ios.a11y.cards": "카드 {n}장",
            "ios.a11y.deck": "덱에 카드 {n}장 남음",
            "ios.a11y.trump": "으뜸패: {suit}",
            "ios.a11y.trumpmark": "으뜸패",
            "ios.a11y.discard": "버린 카드 {n}장",
            "ios.a11y.covered": "{attack}, {defense}(으)로 방어됨",
            "ios.a11y.uncovered": "{attack}, 방어되지 않음",
            "ios.a11y.hiddencard": "뒷면 카드",
            "ios.a11y.facedown": "뒷면 카드",
            "ios.a11y.card": "{suit} {rank}",
            "ios.suit.spades": "스페이드", "ios.suit.hearts": "하트",
            "ios.suit.clubs": "클럽", "ios.suit.diamonds": "다이아몬드",
            "ios.rank.ace": "에이스", "ios.rank.king": "킹",
            "ios.rank.queen": "퀸", "ios.rank.jack": "잭", "ios.rank.ten": "10",
            "ios.tut_next": "알겠어요",
            "ios.tut_done": "게임 시작",
            "ios.tut_1": "두락에 오신 것을 환영합니다. 으뜸패의 가장 낮은 카드가 첫 공격자를 정합니다. 으뜸패는 다른 모든 무늬를 이깁니다.",
            "ios.tut_2": "공격하려면 손패의 카드를 탭하세요. 상대는 그것을 이기거나 전부 가져가야 합니다.",
            "ios.tut_3": "방어하려면 자신의 카드를 탭한 뒤, 이길 공격 카드를 탭하세요. 같은 무늬의 더 높은 카드나 으뜸패로 막습니다.",
            "ios.tut_4": "막을 수 없거나 막지 않으려면 ‘가져오기’를 탭하세요. 공격을 마쳤으면 ‘완료’를 탭하세요.",
            "ios.tut_5": "누구보다 먼저 손패를 비우세요. 마지막까지 카드를 든 사람이 바보입니다. 행운을 빕니다!",
            "ios.bot.random": "마이애미", "ios.bot.handwritten": "뉴욕",
            "ios.bot.robusta": "서울", "ios.bot.firecracker": "마드리드",
            "ios.bot.blackpowder": "빈", "ios.bot.cordite": "상트페테르부르크",
            "ios.bot.octogen": "모스크바",
            "ios.bot.max": "맥스", "ios.bot.km": "모스크바에서 {km} km",
            "ios.bot.km0": "크렘린 그 자체",
        ],
        "zh": [
            // Simplified Chinese. The verbs are the ones Chinese card players
            // reach for - 盖牌 to cover, 拿牌 to take the table, 过 for “I am done” -
            // rather than literal renderings of the English. Cards read SUIT then
            // RANK (黑桃K), which is the order they are said aloud in.
            "play": "开始",
            "offline": "单机",
            "join_by_code": "用代码加入",
            "resume": "继续游戏",
            "replays": "回放",
            "tutorial": "教程",
            "settings": "设置",
            "about": "关于",
            "pass": "转移",
            "pickup": "拿牌",
            "good": "过",
            "attack": "进攻",
            "cover": "盖牌",
            "game_over": "游戏结束",
            "you_win": "你赢了",
            "you_lose": "你成了傻瓜",
            "rematch": "再来一局",
            "share_replay": "分享回放",
            "home": "主页",
            "choose_opponent": "选择对手",
            "start_game": "开始游戏",
            "players": "玩家",
            "thinking": "思考中…",
            "leave_game_title": "离开这局游戏？",
            "leave_game_body": "这局还没有结束。",
            "leave": "离开",
            "cancel": "取消",
            "ios.lobby": "房间",
            "ios.game_code": "游戏代码",
            "ios.ready": "准备好了",
            "ios.add_bot": "添加电脑",
            "ios.share_invite": "分享邀请",
            "join_game": "加入游戏",
            "ios.dashboard": "面板",
            "ios.create_game": "创建游戏",
            "ios.sign_out": "退出登录",
            "ios.online_soon": "在线对战会在后续更新中推出。",
            "ios.reject": "这一手不允许。",
            "ios.you": "你",
            "ios.fool": "傻瓜",
            "ios.nobattle": "无对局",
            "ios.msg.yourmove": "该你了",
            "ios.msg.staged": "已准备好 - 点发送",
            "ios.msg.waiting": "等其他人",
            "ios.msg.waitingfor": "等 {name}",
            "ios.msg.send": "发送这一手",
            "ios.msg.sending": "发送中…",
            "ios.msg.undo": "撤销",
            "ios.msg.newgame": "新游戏",
            "ios.msg.replaylink": "回放链接",
            "ios.msg.replaylink.copied": "链接已复制",
            "ios.msg.pickseat": "你是哪位玩家？",
            "ios.msg.spectating": "观战中 — 从你自己的消息里打开这局才能出牌",
            "ios.msg.thread": "这个对话里有一局游戏",
            "ios.msg.tap": "傻瓜牌 - 点一下开始",
            "ios.msg.damaged": "这局游戏打不开。链接坏了，或者这局是用旧版规则开始的。",
            "ios.msg.open": "打开游戏",
            "ios.msg.fool": "{name} 是傻瓜 - 点一下观看",
            "ios.msg.isfool": "{name} 是傻瓜",
            "ios.msg.moved": "这局游戏已经往下走了。",
            "ios.msg.opennewest": "打开最新的",
            "ios.msg.stale": "较早的一手 - 这局已经往下走了",
            "ios.msg.viewanyway": "仍然查看",
            "ios.msg.yourname": "你的名字",
            "ios.msg.nameprompt": "我们该怎么称呼你？",
            "ios.msg.continue": "继续",
            "ios.msg.seatopen": "空位",
            "ios.msg.joinas": "以 {name} 加入",
            "ios.msg.waitingjoin": "还差 {n} 人",
            "ios.msg.lobbyfull": "位置已满",
            "ios.msg.creategame": "创建游戏",
            "ios.msg.startgame": "开始玩",
            "ios.msg.gameon": "傻瓜牌 - 开局了！点一下开始",
            "ios.msg.joininvite": "傻瓜牌 - 点一下加入",
            "ios.msg.exitgame": "离开",
            "ios.msg.left": "{name} 离开了这局",
            "ios.msg.leftanon": "有玩家离开了这局",
            "ios.msg.invite": "发送邀请",
            "ios.msg.nickname_ph": "你的昵称",
            "ios.msg.entername": "输入昵称",
            "ios.msg.nametoolong": "昵称太长",
            "ios.msg.cardfmt": "{suit}{rank}",
            "ios.msg.seatn": "座位 {n}",
            "ios.msg.mv.attack": "{name} 进攻：{cards}",
            "ios.msg.mv.pass": "{name} 转移：{cards}",
            "ios.msg.mv.cover": "{name} 盖牌：{pairs}",
            "ios.msg.mv.coverpair": "{target} 用 {card}",
            "ios.msg.mv.pickup": "{name} 把牌拿走了",
            "ios.msg.mv.out": "{name} 打完牌了！",
            "ios.msg.mv.good": "{name} 过了",
            "ios.msg.mv.nothing": "{name} 什么也没做",
            "ios.msg.mv.roundover": "这轮结束 - 下一轮 {name} 进攻",
            "ios.msg.sendhint": "发送",
            "ios.msg.started": "{name} 开局了 - 点一下开始",
            "ios.msg.joined": "{name} 加入了 - 点一下加入",
            "ios.rej.turn": "还没轮到你。",
            "ios.rej.pickone": "先选一张牌。",
            "ios.rej.defending": "你在防守 - 盖住这次进攻，或者把牌拿走。",
            "ios.rej.notyours": "这张牌不在你手里。",
            "ios.rej.addrank": "只能加桌上已经有的点数。",
            "ios.rej.cover": "这样打不过 - 出更大的，或者出主牌。",
            "ios.rej.capacity": "进攻的牌比防守方手里的牌还多。",
            "ios.rej.passrank": "只能用点数相同的牌转移。",
            "ios.rej.mustattack": "首攻必须先进攻。",
            "ios.rej.alreadygood": "你已经过了。",
            "ios.rej.notake": "没有牌可拿。",
            "ios.help": "规则",
            "ios.done": "完成",
            "ios.settings.title": "设置",
            "ios.settings.language": "语言",
            "ios.settings.table": "牌桌",
            "ios.settings.table.wool": "羊毛",
            "ios.settings.table.felt": "绿毡",
            "ios.rules.title": "玩法",
            "ios.rules.goal.h": "目标",
            "ios.rules.goal.b": "游戏的最终目标是尽快把手里的牌全部打出去。最后还剩着牌的人就是 дурак，俄语里的“傻瓜”。",
            "ios.rules.setup.h": "开局准备",
            "ios.rules.setup.b": "四人或四人以下时，只用 6 到 A 这些牌，2、3、4、5 全部拿掉。A 在这个游戏里最大。每人发 6 张牌，然后再翻出一张明牌，压在牌堆下面。这张明牌的花色就是主牌花色。主牌花色很特别，防守那一节会讲到。",
            "ios.rules.setup.cap": "牌堆下面压着一张翻开的牌 - 它的花色就是主牌花色。本页所有例子里都是红桃。",
            "ios.rules.start.h": "谁先出牌",
            "ios.rules.start.b": "手里主牌最小的人先出。面对面玩的时候，大家会问谁有 6，然后问谁有 7，以此类推。在这里由游戏自动判定。这个人就是这一轮的首攻。",
            "ios.rules.sword": "剑标记着开这一轮的进攻方。",
            "ios.rules.shield": "盾标记着防守方。",
            "ios.rules.attack.h": "进攻",
            "ios.rules.attack.b": "带剑图标的首攻可以从手里选一张牌，或者选一组点数完全相同的牌，打到左边（顺时针方向）那位玩家面前。那位玩家现在就是防守方，带盾图标，必须应对这次进攻。出牌时点一下选中牌，选中的牌构成合法进攻时进攻按钮就会出现；也可以直接把牌从手里拖到桌上。",
            "ios.rules.attack.ok1": "这位玩家可以用 Q 进攻。",
            "ios.rules.attack.ok2": "也可以两张 K 一起打出去，因为点数相同。",
            "ios.rules.attack.no1": "但不能用 7 和 10 一起进攻，点数不一样。",
            "ios.rules.defend.h": "防守",
            "ios.rules.defend.b": "带盾图标、正在被进攻的那位玩家是防守方。同一时刻只会有一个防守方，别人打到桌上的牌都要由他来应对。防守方只能盖牌、拿牌，或者转移（如果这一桌允许）。防守方不能自己进攻。其他所有人都是进攻方，只能进攻，不能去盖桌上的牌。",
            "ios.rules.defend.b.nopass": "带盾图标、正在被进攻的那位玩家是防守方。同一时刻只会有一个防守方，别人打到桌上的牌都要由他来应对。防守方只能盖牌或者拿牌。防守方不能自己进攻。其他所有人都是进攻方，只能进攻，不能去盖桌上的牌。",
            "ios.rules.cover.h": "盖牌",
            "ios.rules.cover.b": "防守方要用同花色更大的牌，或者任意一张主牌，把桌上的牌一张张盖住。这就是主牌花色特别的地方。盖牌时选中一张牌再点盖牌按钮，或者把手里的牌拖到桌上想盖的那张牌上。常见的误会是以为已经盖住的牌还能被第三张牌再盖一次 - 并不是这样，你永远不会在桌上看到三张一摞。把进攻牌想成一把剑，盖牌想成一面盾：挡下来了，这一摞就结束了。要打只能另起一摞新的进攻。",
            "ios.rules.cover.ok1": "同花色更大的牌可以盖住。",
            "ios.rules.cover.ok2": "主牌能盖住任何别的花色 - 哪怕点数更小。",
            "ios.rules.cover.no1": "主牌的进攻要用更大的主牌来盖 - 这张 7 太小了。",
            "ios.rules.cover.no2": "点数更大，但花色不对 - 盖不住。",
            "ios.rules.throw.h": "加牌",
            "ios.rules.throw.b": "防守方在防守的时候，其他每一位玩家都可以往桌上“加牌”，防守方必须把这些牌也一并防住。规则本身很简单，但要真正想明白得花点时间：如果桌上已经出现了某个点数（比如 A、6、10），而你是进攻方，手里又有这个点数的牌，你就可以把它作为新的一摞进攻加到桌上。完全不用管花色。唯一的限制是防守方手里的牌数：桌上没被盖住的进攻，数量不能超过防守方手里的牌数。可以这样想 - 防守方必须能用一张牌应对一张进攻牌；如果进攻牌太多，这在物理上就不可能，因此也不允许。你可能会想，这样进攻牌岂不是会迅速变多？没错，这正是这个游戏好玩的地方。加牌时点一下那张牌，或者点一组每张点数都已经在桌上出现过的牌，然后按进攻；也可以直接把牌从手里拖到桌上。",
            "ios.rules.throw.ok1": "桌上有 9，所以你的 9 可以加进去 - 花色无所谓。",
            "ios.rules.throw.ok2": "两张 6 一起 - 两摞新的进攻。",
            "ios.rules.throw.ok3": "6 和 9 一起也行 - 这两个点数桌上都已经有了。",
            "ios.rules.throw.no1": "桌上没有 8 也没有 J - 没有能加的牌。",
            "ios.rules.throw.no2": "防守方只剩一张牌，桌上已经有一次进攻等着 - 再加就放不下了。",
            "ios.rules.pickup.h": "拿牌",
            "ios.rules.pickup.b": "如果防守方盖不住所有的牌，或者不想盖，可以按拿牌按钮。这样桌上所有的牌都会进他的手里，已经被盖住的也一样。而且他这一轮会被跳过，下一轮由他左边的人开始进攻。所以要不要拿牌，得想清楚。",
            "ios.rules.pickup.cap": "这里拿牌的话，三张牌都进你手里 - 那对盖住的也一样。",
            "ios.rules.round.h": "一轮结束",
            "ios.rules.round.b": "当桌上所有牌都被盖住，而且所有进攻方都表示不再加牌时，桌上的牌全部进弃牌堆。然后从首攻开始，顺时针轮到每一位进攻方补牌，补到至少 6 张为止，最后才轮到防守方补牌。这些都由游戏自动完成。牌堆摸完之后，大家就可以开始清手里的牌，争取不做最后那个傻瓜。防守方选择拿牌时，这一轮同样结束，进攻方也照样补牌。",
            "ios.rules.pass.h": "转移",
            "ios.rules.pass.b": "在允许 переводной（也就是“转移”）的牌局里，防守方还有一个选择：把这次进攻转移给左边的玩家。要这样做，桌上不能有任何一张牌已经被盖住，而且他手里要有一张与桌上所有进攻牌点数相同的牌。把那张牌放下，盾的图标就会顺时针移到左边那位玩家身上。不过，和进攻牌数有上限一样，如果左边那位玩家手里的牌比转移之后的进攻牌数还少，就不能转移。举个例子：桌上已经有两张进攻牌，左边那位手里只有两张牌，那就不能转移 - 因为转移之后桌上至少会有三张进攻牌（原来的 2 张加上你放下的 1 张），比他手里的牌还多。转移时点一下点数相同的那张牌再按转移按钮，或者把它拖到桌上的空处。",
            "ios.rules.pass.ok1": "桌上是一张 8，你手里也有 8 - 放下去，盾就移走了。",
            "ios.rules.pass.no1": "已经有牌被盖住了 - 来不及转移了。",
            "ios.rules.pass.no2": "你手里没有 8 - 这次只能你自己防。",
            "ios.rules.pass.no3": "转移之后会变成三次进攻，而下一位手里只有两张牌。",
            "ios.rules.end.h": "游戏结束",
            "ios.rules.end.b": "牌堆摸完之后，游戏继续进行。谁把手里的牌全部打完，谁就不会是傻瓜。最后一个手里还有牌的人就是傻瓜。",
            "ios.rules.lobby.h": "房间怎么用",
            "ios.rules.lobby.b": "写上你的名字就算加入。至少两个人加入之后，任何人都可以按开始。游戏一旦开始，就不能再有人加入了。",
            "ios.rules.variant.h": "转移",
            "ios.rules.variant.b": "这一桌玩哪一种傻瓜牌，由房间里决定，勾选框会告诉你玩的是哪一种。勾上就是转移玩法（переводной）：防守方手里如果有和进攻牌点数相同的牌，可以放下去，把整次进攻转移给下一位，改由他来防守。不勾就是加牌玩法（подкидной）：没有转移，防守方要么把桌上的牌全部盖住，要么全部拿走。房间开着的时候，桌上任何人都可以改；游戏一开始就固定了。",
            "ios.rules.fool.h": "傻瓜要付出代价",
            "ios.rules.fool.b": "通常由最小的主牌决定谁先进攻。只有一个例外，也是最古老的一种傻瓜牌规矩：如果一局结束后你按了新游戏，而且原班人马一个不差地又坐了下来，那么最小的主牌就说了不算了 - 改由上一局那个傻瓜右边的人先出，也就是说傻瓜是第一个被进攻的。输了，下一局就直接冲你来。如果在按开始之前有人加入或离开，这一桌就变了，规则也就恢复正常。",
            "ios.lobby.passing": "转移",
            "ios.rules.lbl.table": "桌上",
            "ios.rules.lbl.hand": "你的手牌",
            "ios.rules.defender": "防守方",
            "ios.rules.nextplayer": "下一位",
            "ios.msg.nametaken": "这局里这个名字已经有人用了",
            "ios.a11y.attackfirst": "你先进攻",
            "ios.a11y.on": "开",
            "ios.a11y.off": "关",
            "ios.a11y.defending": "防守中",
            "ios.a11y.attacking": "进攻中",
            "ios.a11y.saidgood": "已过",
            "ios.a11y.thinking": "思考中",
            "ios.a11y.out": "已出局",
            "ios.a11y.cards": "{n} 张牌",
            "ios.a11y.deck": "牌堆还剩 {n} 张",
            "ios.a11y.trump": "主牌 {suit}",
            "ios.a11y.trumpmark": "主牌",
            "ios.a11y.discard": "已弃 {n} 张",
            "ios.a11y.covered": "{attack}，被 {defense} 盖住",
            "ios.a11y.uncovered": "{attack}，没被盖住",
            "ios.a11y.hiddencard": "暗牌",
            "ios.a11y.facedown": "背面朝上的牌",
            "ios.a11y.card": "{suit} {rank}",
            "ios.suit.spades": "黑桃",
            "ios.suit.hearts": "红桃",
            "ios.suit.clubs": "梅花",
            "ios.suit.diamonds": "方块",
            "ios.rank.ace": "A",
            "ios.rank.king": "K",
            "ios.rank.queen": "Q",
            "ios.rank.jack": "J",
            "ios.rank.ten": "10",
            "ios.tut_next": "明白了",
            "ios.tut_done": "开始玩",
            "ios.tut_1": "欢迎来玩傻瓜牌。主牌花色里最小的那张牌决定谁先进攻。主牌大过其他所有花色。",
            "ios.tut_2": "进攻时点一下手里的牌。对手必须盖住它 - 否则就得把牌全拿走。",
            "ios.tut_3": "防守时先点你的一张牌，再点它要盖的那次进攻。同花色更大的牌，或者任意一张主牌，都能盖住。",
            "ios.tut_4": "盖不住或者不想盖？点“拿牌”把桌上的牌拿走。不想再进攻了？点“过”。",
            "ios.tut_5": "比所有人都先把手里的牌打完。最后还剩着牌的人就是傻瓜。祝你好运！",
            "ios.bot.random": "迈阿密",
            "ios.bot.handwritten": "纽约",
            "ios.bot.robusta": "首尔",
            "ios.bot.firecracker": "马德里",
            "ios.bot.blackpowder": "维也纳",
            "ios.bot.cordite": "圣彼得堡",
            "ios.bot.octogen": "莫斯科",
            "ios.bot.max": "马克斯",
            "ios.bot.km": "距莫斯科 {km} 公里",
            "ios.bot.km0": "克里姆林宫本身",
        ],
        "vi": [
            // Vietnamese. Suits and courts use the Vietnamese playing-card names
            // (bích/cơ/tép/rô, át/già/đầm/bồi). The fool is “kẻ ngốc” and not the
            // more everyday “thằng ngốc”: that one carries a masculine classifier,
            // and a table has no business assigning a gender to whoever loses.
            "play": "Chơi",
            "offline": "Ngoại tuyến",
            "join_by_code": "Vào bằng mã",
            "resume": "Chơi tiếp",
            "replays": "Xem lại",
            "tutorial": "Hướng dẫn",
            "settings": "Cài đặt",
            "about": "Giới thiệu",
            "pass": "Chuyển",
            "pickup": "Bốc",
            "good": "Xong",
            "attack": "Tấn công",
            "cover": "Chặn",
            "game_over": "Kết thúc",
            "you_win": "Bạn thắng",
            "you_lose": "Bạn là kẻ ngốc",
            "rematch": "Chơi lại",
            "share_replay": "Chia sẻ bản xem lại",
            "home": "Trang chính",
            "choose_opponent": "Chọn đối thủ",
            "start_game": "Bắt đầu",
            "players": "Người chơi",
            "thinking": "Đang nghĩ…",
            "leave_game_title": "Rời ván này?",
            "leave_game_body": "Ván đấu vẫn đang diễn ra.",
            "leave": "Rời",
            "cancel": "Huỷ",
            "ios.lobby": "Phòng chờ",
            "ios.game_code": "Mã ván",
            "ios.ready": "Sẵn sàng",
            "ios.add_bot": "Thêm máy",
            "ios.share_invite": "Chia sẻ lời mời",
            "join_game": "Vào ván",
            "ios.dashboard": "Bảng điều khiển",
            "ios.create_game": "Tạo ván",
            "ios.sign_out": "Đăng xuất",
            "ios.online_soon": "Chơi trực tuyến sẽ có trong bản cập nhật sau.",
            "ios.reject": "Nước này không hợp lệ.",
            "ios.you": "Bạn",
            "ios.fool": "Kẻ ngốc",
            "ios.nobattle": "không có trận",
            "ios.msg.yourmove": "Đến lượt bạn",
            "ios.msg.staged": "Đã chuẩn bị - bấm Gửi",
            "ios.msg.waiting": "Đang chờ những người khác",
            "ios.msg.waitingfor": "Đang chờ {name}",
            "ios.msg.send": "Gửi nước đi",
            "ios.msg.sending": "Đang gửi…",
            "ios.msg.undo": "Hoàn tác",
            "ios.msg.newgame": "Ván mới",
            "ios.msg.replaylink": "Liên kết xem lại",
            "ios.msg.replaylink.copied": "Đã chép liên kết",
            "ios.msg.pickseat": "Bạn là người chơi nào?",
            "ios.msg.spectating": "Đang xem — mở ván từ tin nhắn của chính bạn để chơi",
            "ios.msg.thread": "Có một ván trong cuộc trò chuyện này",
            "ios.msg.tap": "Durak - chạm để chơi",
            "ios.msg.damaged": "Không mở được ván này. Liên kết bị hỏng, hoặc ván được bắt đầu bằng luật của phiên bản cũ.",
            "ios.msg.open": "Mở ván",
            "ios.msg.fool": "{name} là kẻ ngốc - chạm để xem",
            "ios.msg.isfool": "{name} là kẻ ngốc",
            "ios.msg.moved": "Ván này đã đi tiếp rồi.",
            "ios.msg.opennewest": "Mở nước mới nhất",
            "ios.msg.stale": "Một nước cũ - ván đã đi tiếp",
            "ios.msg.viewanyway": "Vẫn xem",
            "ios.msg.yourname": "Tên của bạn",
            "ios.msg.nameprompt": "Chúng tôi nên gọi bạn là gì?",
            "ios.msg.continue": "Tiếp tục",
            "ios.msg.seatopen": "Còn chỗ",
            "ios.msg.joinas": "Vào với tên {name}",
            "ios.msg.waitingjoin": "Còn chờ {n} người",
            "ios.msg.lobbyfull": "Hết chỗ",
            "ios.msg.creategame": "Tạo ván",
            "ios.msg.startgame": "Bắt đầu chơi",
            "ios.msg.gameon": "Durak - vào ván thôi! Chạm để chơi",
            "ios.msg.joininvite": "Durak - chạm để vào",
            "ios.msg.exitgame": "Rời",
            "ios.msg.left": "{name} đã rời ván",
            "ios.msg.leftanon": "Một người chơi đã rời ván",
            "ios.msg.invite": "Gửi lời mời",
            "ios.msg.nickname_ph": "biệt danh của bạn",
            "ios.msg.entername": "Nhập Biệt Danh",
            "ios.msg.nametoolong": "biệt danh quá dài",
            "ios.msg.cardfmt": "{rank} {suit}",
            "ios.msg.seatn": "Chỗ {n}",
            "ios.msg.mv.attack": "{name} tấn công: {cards}",
            "ios.msg.mv.pass": "{name} chuyển: {cards}",
            "ios.msg.mv.cover": "{name} chặn: {pairs}",
            "ios.msg.mv.coverpair": "{target} bằng {card}",
            "ios.msg.mv.pickup": "{name} đã bốc hết bài",
            "ios.msg.mv.out": "{name} đã hết bài!",
            "ios.msg.mv.good": "{name} đã xong",
            "ios.msg.mv.nothing": "{name} không làm gì",
            "ios.msg.mv.roundover": "Hết vòng - {name} tấn công tiếp",
            "ios.msg.sendhint": "Gửi",
            "ios.msg.started": "{name} đã mở ván - chạm để chơi",
            "ios.msg.joined": "{name} đã vào - chạm để vào",
            "ios.rej.turn": "Chưa đến lượt bạn.",
            "ios.rej.pickone": "Chọn một lá trước đã.",
            "ios.rej.defending": "Bạn đang đỡ - chặn đòn tấn công, hoặc bốc hết lên.",
            "ios.rej.notyours": "Lá đó không có trong tay bạn.",
            "ios.rej.addrank": "Chỉ được thêm hạng bài đã có trên bàn.",
            "ios.rej.cover": "Lá đó không chặn được - đánh lá lớn hơn, hoặc một lá chủ.",
            "ios.rej.capacity": "Số đòn tấn công nhiều hơn số bài của người đỡ.",
            "ios.rej.passrank": "Chỉ được chuyển bằng lá cùng hạng.",
            "ios.rej.mustattack": "Người mở vòng phải tấn công.",
            "ios.rej.alreadygood": "Bạn đã nói xong rồi.",
            "ios.rej.notake": "Không có gì để bốc.",
            "ios.help": "Luật chơi",
            "ios.done": "Xong",
            "ios.settings.title": "Cài đặt",
            "ios.settings.language": "Ngôn ngữ",
            "ios.settings.table": "Mặt bàn",
            "ios.settings.table.wool": "Len",
            "ios.settings.table.felt": "Nỉ xanh",
            "ios.rules.title": "Cách chơi",
            "ios.rules.goal.h": "Mục tiêu",
            "ios.rules.goal.b": "Mục tiêu cuối cùng là đánh hết bài trên tay càng sớm càng tốt. Ai còn bài sau cùng thì người đó là дурак, tiếng Nga nghĩa là kẻ ngốc.",
            "ios.rules.setup.h": "Chuẩn bị ván",
            "ios.rules.setup.b": "Nếu có từ bốn người trở xuống, ván chỉ dùng các lá từ 6 đến Át; 2, 3, 4 và 5 được bỏ ra. Át là lá lớn nhất trong trò này. Mỗi người được chia 6 lá, sau đó rút thêm một lá, lật ngửa và đặt xuống dưới nọc. CHẤT của lá lật ngửa đó chính là chất chủ. Chất chủ rất đặc biệt, phần đỡ bài sẽ nói rõ.",
            "ios.rules.setup.cap": "Một lá được lật ngửa dưới nọc - chất của nó là chất chủ. Trong mọi ví dụ ở trang này là cơ.",
            "ios.rules.start.h": "Bắt đầu ván",
            "ios.rules.start.b": "Ai giữ lá chủ nhỏ nhất thì đi trước. Chơi ngoài đời thì mọi người hỏi ai có 6, rồi ai có 7, và cứ thế. Ở đây ván tự xác định. Người đó là người mở vòng.",
            "ios.rules.sword": "Thanh kiếm đánh dấu người mở vòng tấn công.",
            "ios.rules.shield": "Cái khiên đánh dấu người đỡ.",
            "ios.rules.attack.h": "Tấn công",
            "ios.rules.attack.b": "Người mở vòng, có biểu tượng thanh kiếm, được chọn một lá bất kỳ hoặc một bộ lá CÙNG HẠNG trong tay và đặt về phía người bên trái mình (theo chiều kim đồng hồ). Người đó bây giờ là người đỡ, có biểu tượng khiên, và phải xử lý đòn tấn công. Để đánh, chạm chọn bài rồi bấm nút tấn công hiện ra khi các lá đã chọn hợp lệ. Hoặc chỉ cần kéo bài từ tay ra bàn.",
            "ios.rules.attack.ok1": "Người này có thể tấn công bằng lá Q.",
            "ios.rules.attack.ok2": "Cũng có thể đánh cả hai lá K cùng lúc, vì chúng cùng hạng.",
            "ios.rules.attack.no1": "Nhưng KHÔNG được đánh lá 7 với lá 10 cùng lúc, vì khác hạng.",
            "ios.rules.defend.h": "Đỡ bài",
            "ios.rules.defend.b": "Người đang bị tấn công, có biểu tượng khiên, là người đỡ. Mỗi lúc chỉ có một người đỡ, và mọi lá người khác đặt xuống bàn đều là việc của người đỡ. Người đỡ chỉ được chặn, bốc, hoặc chuyển (nếu bàn cho phép). Người đỡ KHÔNG được tự tấn công. Tất cả những người còn lại là bên tấn công, chỉ được tấn công và KHÔNG được chặn bất kỳ lá nào trên bàn.",
            "ios.rules.defend.b.nopass": "Người đang bị tấn công, có biểu tượng khiên, là người đỡ. Mỗi lúc chỉ có một người đỡ, và mọi lá người khác đặt xuống bàn đều là việc của người đỡ. Người đỡ chỉ được chặn hoặc bốc. Người đỡ KHÔNG được tự tấn công. Tất cả những người còn lại là bên tấn công, chỉ được tấn công và KHÔNG được chặn bất kỳ lá nào trên bàn.",
            "ios.rules.cover.h": "Chặn bài",
            "ios.rules.cover.b": "Người đỡ chặn bài trên bàn bằng cách phủ mỗi lá bằng một lá cùng chất nhưng lớn hơn, hoặc bằng một lá chủ bất kỳ. Đó là điều làm chất chủ đặc biệt. Để chặn, chọn một lá rồi bấm nút chặn. Hoặc kéo lá trong tay tới đúng lá trên bàn mà bạn muốn phủ. Một hiểu lầm thường gặp là tưởng lá đã bị phủ còn có thể bị phủ tiếp bằng lá thứ ba. Không phải vậy - bạn sẽ không bao giờ thấy chồng ba lá trên bàn. Hãy coi lá tấn công là thanh kiếm và lá chặn là cái khiên: đòn đã bị chặn, thế là xong. Chỉ có thể mở đòn tấn công mới, thành đống riêng.",
            "ios.rules.cover.ok1": "Lá cùng chất và lớn hơn thì chặn được.",
            "ios.rules.cover.ok2": "Lá chủ chặn được mọi chất khác - kể cả khi hạng nhỏ hơn.",
            "ios.rules.cover.no1": "Đòn bằng lá chủ phải chặn bằng lá chủ lớn hơn - lá 7 này nhỏ quá.",
            "ios.rules.cover.no2": "Hạng lớn hơn nhưng sai chất - không chặn được gì.",
            "ios.rules.throw.h": "Ném thêm bài",
            "ios.rules.throw.b": "Trong lúc người đỡ đang chặn, mọi người chơi khác đều có thể “ném thêm” bài tấn công mà người đỡ phải chặn nốt. Luật thì đơn giản nhưng phải một lúc mới ngấm: nếu bạn thấy HẠNG của một lá bạn đang cầm (ví dụ A, 6, 10) đã có trên bàn, và bạn thuộc bên tấn công, bạn được đặt lá đó xuống thành một đòn tấn công mới. Đừng bận tâm chút nào về chất. Giới hạn duy nhất là số bài hiện có trong tay người đỡ: số đòn chưa bị chặn trên bàn không được nhiều hơn số lá người đỡ đang cầm. Hãy hình dung người đỡ phải có một lá để đối lại mỗi lá tấn công; nếu bài tấn công quá nhiều thì điều đó là bất khả thi, nên không được phép. Bạn có thể thắc mắc liệu như vậy số bài tấn công có nhân lên rất nhanh không. Đúng vậy, và đó chính là cái hay của trò này. Để ném thêm, chạm một lá hoặc một bộ lá mà hạng của từng lá đều đã có trên bàn, rồi bấm tấn công. Hoặc kéo bài từ tay ra bàn.",
            "ios.rules.throw.ok1": "Trên bàn có lá 9, nên lá 9 của bạn ném vào được - chất không quan trọng.",
            "ios.rules.throw.ok2": "Cả hai lá 6 cùng lúc - hai đòn tấn công mới.",
            "ios.rules.throw.ok3": "Hoặc lá 6 với lá 9 cùng lúc - hạng nào cũng đã có sẵn trên bàn.",
            "ios.rules.throw.no1": "Trên bàn không có 8 cũng không có J - không có gì để ném vào.",
            "ios.rules.throw.no2": "Người đỡ còn một lá và đã có một đòn đang chờ - không còn chỗ cho đòn nữa.",
            "ios.rules.pickup.h": "Bốc bài",
            "ios.rules.pickup.b": "Nếu người đỡ không chặn nổi hết hoặc không muốn chặn, họ có thể bấm nút bốc. Khi đó người đỡ lấy hết bài trên bàn về tay, kể cả những lá đã bị phủ. Và lượt của họ bị bỏ qua, nên vòng sau người bên trái họ sẽ mở đòn. Vậy nên hãy cân nhắc kỹ trước khi bốc.",
            "ios.rules.pickup.cap": "Bốc ở đây thì cả ba lá đều về tay bạn - kể cả cặp đã bị phủ.",
            "ios.rules.round.h": "Hết vòng",
            "ios.rules.round.b": "Khi mọi lá đã bị chặn và không ai còn muốn ném thêm, toàn bộ bài trên bàn đi vào chỗ bài bỏ. Sau đó mọi người rút bài, bắt đầu từ người mở vòng rồi theo chiều kim đồng hồ qua hết bên tấn công, rút cho tới khi có ít nhất 6 lá. Người đỡ rút sau cùng. Việc này ván tự làm. Khi nọc đã cạn, mọi người bắt đầu đánh hết bài của mình để khỏi thành kẻ ngốc. Vòng cũng kết thúc nếu người đỡ chọn bốc; khi đó bên tấn công vẫn rút bài như trên.",
            "ios.rules.pass.h": "Chuyển đòn",
            "ios.rules.pass.b": "Ở ván có luật переводной, tức là “chuyển đòn”, người đỡ còn một lựa chọn nữa: đẩy đòn tấn công sang người bên trái mình. Muốn vậy, trên bàn chưa được có lá nào bị phủ, và họ phải có một lá CÙNG HẠNG với tất cả các lá tấn công đang trên bàn. Đặt lá đó xuống là biểu tượng khiên đi theo chiều kim đồng hồ sang người bên trái. Tuy nhiên, giống như có giới hạn về số lá tấn công, không được đẩy đòn nếu người bên trái cầm ít bài hơn số đòn sẽ có sau đó. Ví dụ, nếu trên bàn đã có hai lá tấn công và người bên trái chỉ cầm hai lá thì không được, vì sau đó bàn sẽ có ít nhất ba đòn (2 lá cũ cộng 1 lá vừa đặt), nhiều hơn số bài họ cầm. Để làm việc này, chạm lá cùng hạng rồi bấm nút chuyển, hoặc kéo lá cùng hạng ra chỗ trống trên bàn.",
            "ios.rules.pass.ok1": "Trên bàn là lá 8 và bạn cũng có lá 8 - đặt xuống là cái khiên đi tiếp.",
            "ios.rules.pass.no1": "Đã có lá bị phủ rồi - muộn mất rồi.",
            "ios.rules.pass.no2": "Trong tay không có lá 8 - đòn này bạn phải tự đỡ.",
            "ios.rules.pass.no3": "Làm vậy sẽ thành ba đòn, mà người kế tiếp chỉ cầm hai lá.",
            "ios.rules.end.h": "Kết thúc ván",
            "ios.rules.end.b": "Khi nọc đã cạn, ván vẫn tiếp tục. Ai đánh hết bài thì thoát, không phải là kẻ ngốc. Người cuối cùng còn cầm bài chính là kẻ ngốc.",
            "ios.rules.lobby.h": "Phòng chờ hoạt động thế nào",
            "ios.rules.lobby.b": "Thêm tên của bạn để vào. Khi đã có ít nhất hai người, ai cũng có thể bấm Bắt đầu. Sau khi ván bắt đầu thì không ai vào được nữa.",
            "ios.rules.variant.h": "Chuyển đòn",
            "ios.rules.variant.b": "Phòng chờ quyết định bàn này chơi kiểu Durak nào, và ô đánh dấu cho biết là kiểu nào. Có dấu tích là ván có chuyển đòn (перевод): người đỡ nếu cầm lá cùng hạng với đòn tấn công thì được đặt xuống và đẩy cả đòn sang người kế tiếp, và giờ người đó phải đỡ. Bỏ dấu tích là ván ném thêm (подкидной): không có lựa chọn đó, nên người đỡ phải chặn hết mọi lá trên bàn hoặc bốc tất cả lên. Khi phòng chờ còn mở, ai ngồi ở bàn cũng đổi được; ván bắt đầu là cố định.",
            "ios.rules.fool.h": "Kẻ ngốc phải trả giá",
            "ios.rules.fool.b": "Bình thường lá chủ nhỏ nhất quyết định ai tấn công trước. Có đúng một ngoại lệ, và đó là kiểu công lý Durak xưa nhất: nếu bạn bấm Ván mới sau khi một ván kết thúc và đúng những người đó lại ngồi vào, thì lá chủ nhỏ nhất chẳng quyết định gì cả. Người ngồi bên phải kẻ ngốc của ván trước sẽ mở đòn, nghĩa là kẻ ngốc bị tấn công đầu tiên. Thua là ván sau đánh thẳng vào bạn. Nếu có ai vào hoặc rời đi trước khi bấm Bắt đầu thì bàn đã khác, và luật thường quay lại.",
            "ios.lobby.passing": "Chuyển đòn",
            "ios.rules.lbl.table": "trên bàn",
            "ios.rules.lbl.hand": "bài của bạn",
            "ios.rules.defender": "Người đỡ",
            "ios.rules.nextplayer": "Người kế tiếp",
            "ios.msg.nametaken": "tên này đã có người dùng trong ván",
            "ios.a11y.attackfirst": "Bạn tấn công trước",
            "ios.a11y.on": "bật",
            "ios.a11y.off": "tắt",
            "ios.a11y.defending": "Đang đỡ",
            "ios.a11y.attacking": "đang tấn công",
            "ios.a11y.saidgood": "đã xong",
            "ios.a11y.thinking": "đang nghĩ",
            "ios.a11y.out": "đã hết bài",
            "ios.a11y.cards": "{n} lá",
            "ios.a11y.deck": "còn {n} lá trong nọc",
            "ios.a11y.trump": "chủ {suit}",
            "ios.a11y.trumpmark": "chủ",
            "ios.a11y.discard": "{n} lá đã bỏ",
            "ios.a11y.covered": "{attack}, bị {defense} phủ",
            "ios.a11y.uncovered": "{attack}, chưa bị phủ",
            "ios.a11y.hiddencard": "lá úp",
            "ios.a11y.facedown": "lá úp mặt",
            "ios.a11y.card": "{rank} {suit}",
            "ios.suit.spades": "bích",
            "ios.suit.hearts": "cơ",
            "ios.suit.clubs": "tép",
            "ios.suit.diamonds": "rô",
            "ios.rank.ace": "át",
            "ios.rank.king": "già",
            "ios.rank.queen": "đầm",
            "ios.rank.jack": "bồi",
            "ios.rank.ten": "mười",
            "ios.tut_next": "Đã hiểu",
            "ios.tut_done": "Bắt đầu chơi",
            "ios.tut_1": "Chào mừng đến với Durak. Lá nhỏ nhất của chất chủ quyết định ai tấn công trước. Lá chủ ăn được mọi chất khác.",
            "ios.tut_2": "Để tấn công, chạm một lá trong tay. Đối thủ phải chặn được nó - hoặc bốc hết lên.",
            "ios.tut_3": "Để đỡ, chạm một lá của bạn rồi chạm vào đòn mà nó chặn. Lá cùng chất lớn hơn, hoặc một lá chủ bất kỳ, đều phủ được.",
            "ios.tut_4": "Không chặn được hoặc không muốn chặn? Bấm Bốc để ôm hết bài lên. Không tấn công nữa? Bấm Xong.",
            "ios.tut_5": "Hãy đánh hết bài trước mọi người. Người cuối cùng còn cầm bài là kẻ ngốc. Chúc may mắn!",
            "ios.bot.random": "Miami",
            "ios.bot.handwritten": "New York",
            "ios.bot.robusta": "Seoul",
            "ios.bot.firecracker": "Madrid",
            "ios.bot.blackpowder": "Vienna",
            "ios.bot.cordite": "Saint Petersburg",
            "ios.bot.octogen": "Moskva",
            "ios.bot.max": "Max",
            "ios.bot.km": "Cách Moskva {km} km",
            "ios.bot.km0": "Chính điện Kremlin",
        ],
    ]
}
