import CoreGraphics
import CUttt
import SwiftUI

/// The sheet. Generated by the kernel so both phones are looking at the same
/// piece of paper, cached because it never changes.
public enum UtttPaper {
    private static var cache: [Int: CGImage] = [:]

    public static func image(side: Int) -> CGImage? {
        if let c = cache[side] { return c }
        var px = [UInt8](repeating: 0, count: side * side * 4)
        px.withUnsafeMutableBufferPointer { uti_paper($0.baseAddress, Int32(side), Int32(side)) }
        guard let provider = CGDataProvider(data: Data(px) as CFData),
              let img = CGImage(width: side, height: side, bitsPerComponent: 8,
                                bitsPerPixel: 32, bytesPerRow: side * 4,
                                space: CGColorSpaceCreateDeviceRGB(),
                                bitmapInfo: CGBitmapInfo(rawValue:
                                    CGImageAlphaInfo.premultipliedLast.rawValue),
                                provider: provider, decode: nil,
                                shouldInterpolate: true, intent: .defaultIntent)
        else { return nil }
        cache[side] = img
        return img
    }
}

public struct UtttSheet<Content: View>: View {
    let content: Content
    public init(@ViewBuilder content: () -> Content) { self.content = content() }
    public var body: some View {
        content.background(
            GeometryReader { geo in
                if let img = UtttPaper.image(side: 420) {
                    Image(decorative: img, scale: 1)
                        .resizable()
                        .frame(width: geo.size.width, height: geo.size.height)
                        .clipped()
                } else {
                    Color(red: 0.969, green: 0.965, blue: 0.949)
                }
            }
        )
    }
}
