import CoreGraphics
import CUttt
import SwiftUI

/// The sheet. Generated by the kernel so both phones are looking at the same
/// piece of paper, cached because it never changes.
public enum UtttPaper {
    private static var cache: [Int: CGImage] = [:]

    public static func image(side: Int) -> CGImage? {
        if let c = cache[side] { return c }
        UtttLog.note("paper", "\(side)")
        defer { UtttLog.note("paper done") }
        var px = [UInt8](repeating: 0, count: side * side * 4)
        px.withUnsafeMutableBufferPointer { uti_paper($0.baseAddress, Int32(side), Int32(side)) }
        guard let provider = CGDataProvider(data: Data(px) as CFData),
              let img = CGImage(width: side, height: side, bitsPerComponent: 8,
                                bitsPerPixel: 32, bytesPerRow: side * 4,
                                space: CGColorSpaceCreateDeviceRGB(),
                                bitmapInfo: CGBitmapInfo(rawValue:
                                    CGImageAlphaInfo.premultipliedLast.rawValue),
                                provider: provider, decode: nil,
                                shouldInterpolate: true, intent: .defaultIntent)
        else { return nil }
        cache[side] = img
        return img
    }
}

public struct UtttSheet<Content: View>: View {
    let content: Content
    public init(@ViewBuilder content: () -> Content) { self.content = content() }
    /// HOW FAR THE PAPER RUNS PAST THE TOP OF ITS BOX.
    ///
    /// The drawer resizes at the compositor's rate and SwiftUI lays out at
    /// its own, so during a collapse the sheet's top edge is above where our
    /// background thinks it is for a frame or two - and the gap reads as a
    /// black band at the top of the napkin. The paper is simply taller than
    /// the box and anchored to the BOTTOM, which is the edge that does not
    /// move; there is nothing to synchronise because nothing has to arrive on
    /// time.
    private let bleed: CGFloat = 220

    public var body: some View {
        content.background(
            GeometryReader { geo in
                Group {
                    if let img = UtttPaper.image(side: 420) {
                        Image(decorative: img, scale: 1).resizable()
                    } else {
                        Color(red: 0.969, green: 0.965, blue: 0.949)
                    }
                }
                /* TALLER THAN THE BOX AND GROWING UPWARDS. The bottom edge
                 * stays put - it is the one that does not move - and the top
                 * runs off past whatever the drawer is doing. Nothing clips
                 * it, which is the point: a background that ends exactly at
                 * its own bounds shows black the moment the bounds are stale
                 * by a frame. */
                .frame(width: geo.size.width, height: geo.size.height + bleed)
                .offset(y: -bleed)
            }
        )
    }
}
