import CoreGraphics
import CUttt
import UIKit

/// The sheet. Generated by the kernel so both phones are looking at the same
/// piece of paper, cached because it never changes.
public enum UtttPaper {
    private static var cache: [Int: UtttBitmap] = [:]

    /// THE PAPER'S FLAT COLOUR, for everything that is painted before the
    /// grain is ready or where the grain cannot reach: the host view on the
    /// very first frame, the safe area under the sheet, and any frame in which
    /// the drawer has moved and the layout has not. A host view left clear shows
    /// Messages' dark drawer through it - the black band under every sheet.
    public static let flat = UIColor(red: 0.969, green: 0.965, blue: 0.949, alpha: 1)

    /// The kernel's paper, painted straight into the one bitmap the
    /// compositor shows (UtttBitmap) - no malloc copy, no render-server copy.
    public static func bitmap(side: Int) -> UtttBitmap? {
        if let c = cache[side] { return c }
        UtttLog.note("paper", "\(side)")
        defer { UtttLog.note("paper done") }
        guard let bm = UtttBitmap(width: side, height: side, rows: { base, stride in
            uti_paper_bgra(base.assumingMemoryBound(to: UInt8.self), Int32(side), Int32(side), Int32(stride))
        }) else { return nil }
        cache[side] = bm
        return bm
    }
}

